### ISSUE TITLE
혹시 생성한 브랜치를 공유 한다면 push 전용 브랜치를 만드는건 어떨까요?

### ISSUE THREAD

**Issue by won-hj** [won-hj/mon2tor#16]
뭐 하나 할 때마다 브랜치를 하나하나 만들어서인지 몇 개 하지도 않았는데도
이게 맞는건지 헷갈립니다...

push 용으로 큰 브랜치를 만들고 그 push브랜치에서 작업할 브랜치를 따로 생성하여 관리하는건 어떨까 싶습니다
이후 작업이 완료되면 push를 위한 브랜치에 push를 하며 통합시키는 것입니다.
push에서 메인으로는 굵직한 것을 마무리하면 그 때 push하는게 더 좋을 것 같아요..,,, 

전달이 좀 이상하게 되고있는데 다들 무슨 의미인지 잘 알아들으셨다고 믿고
혹시라도 무슨 말인지 모르겠다면 말해주세용.........

**Comment by dozzzang** [comment]
하위 브랜치를 생성한다는 말씀이신가요?

**Comment by won-hj** [comment]
제목 이상하게 써진걸 이제봤네요 
뒤쪽 내용 적고 앞쪽을 추가했는데 이상한걸 못느꼈습니다...

하위 브랜치를 만드는 것이 맞습니다
특정 브랜치를 만들어 관리하다가 이 브랜치에서만 메인으로 push하는거죠

**Comment by dozzzang** [comment]
저도 처음에 그 생각을 굉장히 많이 했습니다.
하지만 하지 못한 것은 첫 번째로 교수님께서 올려주신 참고할만한 우수사례를 보니 하위 branch를 따로 따지않은 것 같아서이고
두 번째는 만약에 예를 들어 feature_graph에서 feature_graph_2013 branch를 하위로 땄다고 했을 때 feature_graph_2013_branch를 어디로 push하냐가 고민이었습니다. 어디로 푸쉬하든 그냥 branch를 하나만 따서 push하는 것과 다르지 않다고 생각했거든요.

**Comment by won-hj** [comment]
feture_graph 브랜치에서 feature_graph_2013 브랜치를 만든 후엔 feature_graph로 push 하면 될 것 같습니다
브랜치 간 push도 가능하고 pr도 가능한 것으로 알고 있습니다 !!!
