### ISSUE TITLE
폴더를 만들어야 하는 경우

### ISSUE THREAD

**Issue by dozzzang** [won-hj/mon2tor#17]
제가 10개년 csv파일을 merge한 후에 폴더를 만들어서 파일을 옮겼는데 결국 이는 main에서 하게 되는 일이어서 지양해야할 것 같습니다.
폴더를 만들 소요가 있는 경우에도.. local에서 폴더를 만들어 넣고 PR해야하나봐요.
![image](https://user-images.githubusercontent.com/74997120/232263445-c5ed9598-6bf0-477b-9823-4ea77827f369.png)

**Comment by won-hj** [comment]
아 네 폴더도 만들고나서 풀리퀘스트까지 해야하는거같아요
저도 putty에서 확인좀 하다가 적용이 잘 안돼서 지우고 다시 클론 만들었어요

그래서 제가 메인에 적용시키기 전에 브랜치 하나 만들어서 거기서 이것저것 하는게 어떠냐는 이슈를 만들었습니다!

**Comment by dozzzang** [comment]
이미 알고 계셨군요! 이번 PR은 폴더를 만들어서 했습니다 main에 저렇게 커밋내역이 남는게 아쉽네요 ㅠㅠ
