### ISSUE TITLE
bokeh api를 이용하여 html로 그림 그리는거 되시는분 계신가요?? 

### ISSUE THREAD

**Issue by won-hj** [won-hj/mon2tor#23]
https://frhyme.github.io/python-libs/python_bokeh_tutorial/#html-%ED%8E%98%EC%9D%B4%EC%A7%80%EB%A1%9C-%EB%BD%91%EC%95%84%EB%82%B4%EA%B8%B0

올려주셨던 예제랑 사용자설명서 보면서 예제를 따라하고 있는 상황이었는데

블로그 기준으로 file_html()로는 그림이 출력되어도 json으로 json.dumps()나 render_template()하는건 그림이 전혀 그려지지 않아요...

제가 생각해본 것 중에서 무슨 라이브러리를 설치하지 않았거나 버전이 맞지 않는 것이 아닌가 추측하고는 있는데

뭘 어떻게 했어야하는지 잘 모르겠네요...

찾아봐도 vs코드 기준으로는 안나오고 주피터로만 나오는 것 같아서 무작정 따라하는 것도 조금 안맞는 느낌이기도 하고

암튼 지금 진전이 전혀 안되고 있는 상황입니다......

그림 예제 후딱 실행해보고 csv 파일로 각 년도 보여주는걸 응용해보려 했는데 초장부터 잘 안되네요...

혼자로는 왜 그림이 안그려지고 json형식 자체로만 나오는지 모르겠습니다...
라이브러리 적용이 안된다...라기엔 예시 그대로 복사했고 간단하게 표현해주는 것인데도 모두 그림이 그려지지 않기 때문에 그 외로 추가적인 설치과정이 생략되었나 라는 것 밖에 생각이 안납니다 

도움이 필요합니다....

**Comment by dozzzang** [comment]
시도했던 코드 커밋해주실 수 있나요? 저도 해보고 혁주님 분기로 커밋해드릴게요
그리고 어떤 html파일에 삽입하려 하고 있나요?

**Comment by won-hj** [comment]
엇 커밋만 해도 공유가 되는것나요...? 풀리퀘스트까지 해야 되는줄 알았네용......
어제 하다가 너무 지저분해지고 단순 예제만 따다 실행한 것이어서 지웠습니다.
어차피 블로그와 가이드 내용이 전부이기 때문에 쪼끔 이따가 다시 해보고 커밋하겠습니다!!

html은 블로그 내용에도 나와있습니다.
간단히 요약하자면 제가 해본 결과 이미지를 만드는 링크를 가져오는 방식인데요.
내용 보시면 아시겠지만 쓰는 url은 bokeh_json_item와 _bokeh_json_item_ 두 가지이고,  _/bokeh_json_item_가 그림만 그려주는 것이고 _/_bokeh_with_json__에서 그림을 가져오는 것으로 이해하고 있습니다.
따라서 예제 자체로는 _/bokeh_with_json_ 을 실행하면 그 안에  _/bokeh_json_item_ 의 내용이 들어가는 것입니다.

**Comment by won-hj** [comment]
헉 그새 자버렸습니다 죄송해요
부랴부랴 켜서 확인해보는데 그림 띄워주는 부분에는 크게 건들 필요 없어보여 약간의 주석만 추가했습니다.
보시면 아실거라고 믿어요!

커밋은 했는데 제가 이해한 것이 맞는지는 잘 모르겠네요 ....

**Comment by won-hj** [comment]
버전문제였습니다
사용하는 bokeh 버전은 3.1.0인데 href에서는 1.0.4였기 때문이었네요
결과만 본다고 대충 복사붙여넣기 한 부분인데 생각치도 못하고 있었습니다......
