### ISSUE TITLE
그래프 UI 문제와 예측 시점 논의

### ISSUE THREAD

**Issue by dozzzang** [won-hj/mon2tor#27]
![image](https://github.com/won-hj/mon2tor/assets/74997120/be7bd9cb-dedf-41c9-8391-c382c9dd67b0)
형광펜 칠한 부분이 마우스를 갖다대면 정보를 제공하는 hover 기능 부분인데 아무리해도 구분이 안되네요 plot자체를 구분시켜야할 것 같은데 위의 hover을 클릭해서 비활성화 시키면 "사망자 수"라는 툴팁만 나오고 아래 hover을 클릭해서 비활성화 시키면 "출생아 수"라는 툴팁만 나옵니다. 어쨌거나 변경할 수 있는 기능자체는 있기 때문에 냅두려고 하는데 어떠신가요?

추가로 현재 2023-2027 그래프를 생성했는데
이후 2027-2031 2031-2035 2035-2039 2039-2043 그래프 까지만 생성해보고자 합니다. 시기는 적절한 듯 한가요?

**Comment by won-hj** [comment]
사망자수와 출생아수가 배타적으로 표현되는데 두 기능 모두 출력할 수 있기 때문에 그대로 하신다는 말씀이시죠?
저는 어차피 출력되는 내용은 똑같고 한번에 비교할 수 있도록 하면 좋겠지만 의도상 그렇다고 할 수 있는 부분이고 출력이 안되는 것도 아니니 그렇다면 어쩔 수 없다는 생각이 듭니다...

그리고 5년 단위로 43년도 까지만 생성하신다고 되어있는데 5년단위가 깔끔하고 괜찮다고 생각해요
년도가 더러워보이긴한데 23년기준이니 이건 어쩔 수 없는 것이고 5년단위 4개면 충분한 것 같습니다.

**Comment by dozzzang** [comment]
네~ 을중 씨 의견 마저 듣고 close할게용

**Comment by KimEulJoong** [comment]
네 알겠습니다
