### ISSUE TITLE
지금 확인해보니 커밋했던 것들이 인사이트에 뜨지 않네요... 

### ISSUE THREAD

**Issue by won-hj** [won-hj/mon2tor#28]
풀리퀘스트 안해도 커밋내역 뜬다고 알아서 git commit -m "msg" 로만 했는데 혹시 더 했어야 하는게 있을까요..?

**Comment by dozzzang** [comment]
아! commit뿐만 아니라 network 그래프 보시면 remote branch에 commit된 걸 push해야합니다.
즉, local에서 commit하고 remote branch에 push해야합니다!
ex) 제가 만약 로컬 branch인 feature_create에서 작업하여 add하고 commit했다면 push origin feature_create 해주어야 내역이 남습니다!

**Comment by KimEulJoong** [comment]
add commit 까지만 하고 push를 안해서 기록이 안남았다는 내용인가요?

**Comment by won-hj** [comment]
감사합니다 !!!!!!! push 를 풀리퀘스트하는 것으로만 생각해버렸네요 ....
