### ISSUE TITLE
✅주제 구체화 하기

### ISSUE THREAD

**Issue by dozzzang** [won-hj/mon2tor#3]
# 주제를 나타낼 방식을 적어주세요.
ex) 웹에 어떤 기능을 넣으면 좋을 지

# 어떤 언어를 사용하면 좋을 지 적어주세요.
ex)
- Python 
- (HTML)/CSS

# ETC
ex) 기타 하고 싶은 말이 있다면 적어주세요. ~~기능을 ~~언어로 구현해보면 어떨까요?

**Comment by dozzzang** [comment]
Android와 IOS 모두 고려해야하는 앱보다는 웹이 더 낫다고 생각했습니다.
웹에는 HTML/CSS/JAVASCRIPT를 고려중입니다. 가능하다면 리액트도 사용하고 싶습니다.
웹을 통해 1. 저출산 과거 데이터를 이용하여 미래 출산 예측 그래프와 표 2. 고령화 과거 데이터를 통해 미래 노인 인구비율 예측 그래프와 표를 보여주고 싶습니다.
우선, 큰 틀은 이렇고 UI부분은 다 같이 고민해보면 좋겠습니다.
위 내용을 구현하는데 Python을 이용할 예정입니다.

추가로, 차별화 전략으로
1. 개인화된 예측 (나이를 입력하면 ~년 뒤 미래의 특정 산업 동향 제공)
2. 커뮤니티 ( 1 기능을 제공함으로써 서로 의견을 공유할 수 있는 간단한 커뮤니티 기능을 넣고 싶습니다. 다만 그렇게 된다면, 백엔드가 필요할 것 같네요.)
2-1. 커뮤니티 회원 포인트제? 사실 이 부분은 어려워 보이는데.. 커뮤니티를 이용해 쓴 글,댓글에 따라 포인트를 제공하여 저희가 제공하는 resource 중 원하는 resource를 주기적으로 받아볼 수 있는 기능을 가능하다면 제작해보고 싶습니다.
3. 2-1내용보다는 조금 더 쉽게 단순히 저출산,고령화에 관한 대한민국 업계의 동향이나 사회의 흐름의 단순 정보 제공을 해주고 싶습니다.

위 기능을 통합한다면, 한국의 특정 고령화,저출산 측면에 집중하는 다른 기사나 영상보다 개인화되고 사용자가 흥미로운 방식으로 상호작용하는 방식으로 미래를 예측하고 영감을 줄 수 있을 것 같습니다.

하지만 우선적으로 가장 큰 목표는 '예측'이라는 키워드에 맞게 Python을 이용하여 예측 데이터를 제공하는 것입니다.

**Comment by won-hj** [comment]
### **_주제를 나타낼 방식_**

- 데이터를 어디서 가져올까요?
어떤 데이터를 활용할 것이냐가 많이 관여할 것이라 봅니다.

- 누가 사용할까요? 주제의 키워드를 보면 일반 사용자보단 연구직이라고 봅니다. 따라서 만들 기능은 누구를 위한 것인지 생각해보는 시간을 가지면 좋을 것 같습니다.


예측을 하는 것이 중요하지 결과가 얼마나 잘 맞아떨어지느냐가 중요한게 아니기 때문에
1. 기본적으로 지금까지의 출산률과 고령화와 비교해 미래에는 어떻게 될 것이다 라는 수치를 하나 보여주면 될 것 같습니다.
2. 어차피 비슷비슷할 것이기 때문에 관련해서 몇가지(인구분포나 인구 중 외국인/귀화자 등 비율 같은) 정도로 더 보여줄 수 있을 듯 싶습니다.

추가적으로 연구를 목적으로 한다면 활용할 가치가 있어야 하겠지만 
데이터를 모으는 용도도 아니면서 그정도 실력도 없는데다가 기간도 그렇고 여러 조건이 제한적이어서 일반사용자들이 간단하게 사용하는 것이 적절하다고  생각합니다.


근데 그럼 사실 일반 사용자 입장에서는 이런 저출산이 어떻고 그런그런 문제가 필요는 없긴 할거거든요........
그래도그래도 쥐어짜보자면 어떤 주제에 대한 커뮤니케이션 기능을 만들면 될 것 같습니다.

 - > 게시판같은거 만든다! -> 로그인 필요 -> 사용자 구분??? (관리자/일반사용자는 당연히 만드는데 이걸 목적에 따라 일반사용자와 연구자??같은 정도로 더 만드냐???) >>>>> 게시판 사용은 익명으로 하는 것도 괜찮다고 생각합니다
 - > 뭔가 시각적인 요소가 필요한데 위의 출/고 추이 그래프라던지, 추가적인 정보들을 보여주는 것 자체만으로도 좋은 것 같습니다.
 - > 도현씨처럼 동향같은걸 보여주는 것도 괜찮은 방법이라고 생각합니다. 경제정보센터의 특집(https://eiec.kdi.re.kr/publish/naraList.do?fcode=00002000040000100001)이나 이슈(https://eiec.kdi.re.kr/publish/naraList.do?fcode=00002000040000100009) 정도 크롤링해서 몇가지씩만 보여주는 것도 괜찮다고 봅니다.
 - > 무엇보다 지금 생각난건데 저/고의 결과라고 한다면 태어나는 사람이 줄고 죽거나 죽을 사람이 많아진다는 것이에요. 그렇기 때문에 이걸 이용해서 현재 위치 기준으로 주변 장례식장이나 병원같은 시설을 지도에 보여주거나 예약같이(허접해도문제없겠죠) 충분히 활용할 수 있는 기능도 괜찮을 것 같습니다.

경제정보센터의 [토픽분석](https://eiec.kdi.re.kr/bigdata/topicView.do?bidx=21&pg=1&pp=5)을 보면 참고할만한 예시가 딱 나오는 것 같아요
이런 식으로 보여주는 것도 좋을 것 같습니다. ('이렇게'가 아닙니다!!)


### **_어떤 언어를 사용하면 좋을 지_**

저는 화면 구성을 생각하면 앱을 만드는게 좀 더 편하지 않나 생각합니다.
안드로이드와 IOS를 모두 구상해야 한다기 보단 그냥 안드로이드 기준으로 만든다 라고만 하면 될 것 같습니다.

> 일단 무엇보다 이런 화면 자체를 표현해주는 것이 html과 js 같은거고 그걸 서버로부터 요청한 어떤 데이터를 받아와서 화면에 보여주는 역할을 하는 것이라고 알고 있는데요 
> 그렇기 때문에 단순히 '화면 구성만 하겠다' 라고 할 경우에나 html을 사용하고 그런식으로 할 수 있을 것 같습니다.

따라서 두 가지 선택지를 생각해보자면
- 앱을 만들 경우 저는 코틀린을 사용하는게 더 좋지 않을까 싶고
- 웹을 만든다면 파이썬을 바탕으로 플라스크라는 프레임워크를 이용해 구조를 만든 후 html로 화면구성까지구현하는게 어떨까 싶습니다.

그리고 서비스를 제공한다고 한다면 서버를 용도와 상황에 전부 나눠서 관리하거나 적절히 묶어두는 것이 좋겠지만은 여건상 마땅치 않으니 
서버에 대해 고려를 한다면 개발 환경에 전부 몰아넣거나 해야 하지 않을까 싶습니다.

이 경우에는
1. 아얘 서버용으로 싸게싸게 구비만 해두고 사용하거나
- 이 경우 초기에 비용이 조금 들고 장소같은 문제가 있을 것 입니다.
2. 가상환경을 이용해서 사용할 수 있겠습니다.
 - 이 경우 설치 비용은 문제 없기만 개발 환경의 스펙에 따라 버벅인다던지 안된다는 경우가 있을  수 있습니다.

무엇보다 제가 git 생태계를 잘 알지 못해서 어떤 식으로 사용할 수 있을지 정확히 모르는 상태입니다.
그래서 서버단도 깃으로 관리하는지 잘 모르는 상황이고 혹시 아는거 있으시면 알려주시면 감사합니다.....

### **_ETC_**

마지막으로 

을중씨가 시간을 얼마나 확보할 수 있냐가 중요한 점 같고 파이썬은 좀 하신다고 기억은 하고 있기 때문에 웹을 만드는게 좀 더 낫지 않을까 생각은 하고는 있습니다. 
그런데 어차피 저도 그렇고 배우면서 적응하는 과정이기 때문에 저는 어떤 언어여도 괜찮을 것 같습니다.
따라서 도현씨처럼 html css js 이런거로만 사용해서 만든다 라고만 해도 괜찮다고 알아주셨으면 좋겠고....

근데 궁금한게 이 범위를 어디부터 어디까지 해야 좋을지 인데요.
웹을 만든다 라고 해서 단순히 화면만 뿌려주는게 마는게 아니기도 하고 
이 수업에서 요구하는게 어디부터 어디까지 인지 정확히 잘 알지 못하는 상황이기 때문에 
그 '어디부터 어디까지 만들것이냐'가 제일 중요한 것 같아요 
근데 이건 의견을 종합해보면 금방 확정될 것 같아 걱정은 안드네요 갑자기

또...
우리 그 뭐 환경 설정하고 그런거 다 맞추는게 굉장히 중요할거에요
그러니까 자바를 쓰던 뭘 쓰던 버전 굉장히 중요하고 또 도구도 중요하고 도구의 버전도 중요하다고 생각하고 있습니다.
그렇기 때문에 개발도구는 무슨 버전의 뭘 쓰고 언어도 어떤 버전을 쓰고 그런것도 같이 결정하는게 좋겠어요.


두세시간정도 계속 고민하면서 좀 두서없이 쓰고 지우고 하다보니 충분히 전달이 안될 수 있습니당... .. 
어렵네요 .. 그래도 4월1일이라고 딱 시작할 필요는 없으니까 적어도 수요일까지는 마무리하고 시작할 수 있도록 합시다!!!!!!!!!!!!!!!!!

**Comment by dozzzang** [comment]
안녕하세요. 잘 읽어보았습니다. 위 내용에 대한 저의 의견입니다.
---
1.우선 데이터를 어디서 가져오냐는 질문에는 공공데이터를 활용할 것인데 10년치를 활용할 생각입니다. 데이터 분석에 쓰이는 csv파일이 없어 엑셀로 직접 만들어야 할 것 같기도 합니다.

2.사용하는 대상에 관해서는 연구직 뿐만 아니라 저희같은 일반 서민들도 최근 대두되는 사회문제에 대해 구체적으로 알고 싶어 활용해보지 않을까요?

3.어차피 비슷비슷하다는 말씀은 해석하기에 따라 받아들여지는 것이 다를 것 같은데, 저희가 주제를 정한 이유가 고령화와 저출산이 가속화되가고 있다는 것은 알지만 정확한 수치로 그리고 가시적으로 받아들이면 좋겠다였으니 구체화해서 보여준다는 것이 의미가 있을 것 같습니다.

4.저는 일반사용자에게도 충분히 가치있다고 느낍니다. 오히려 연구직 분들은 저희의 데이터분석이 형편없다고 안 보실지도 모르겠습니다. 예로 유x브에 x카월드라는 크리에이터가 주기적으로 저출산 문제를 다루고 있는데 조회수가 굉장히 높습니다. 일반 사용자에게도 굉장히 관심있는 주제라고 보여집니다.

5.게시판의 경우 만들면 정말 좋겠지만 백엔드가 필요하고 이 부분의 경우 저도 공부를 많이해야하기에 혁주님의 말씀대로 조율해나가는 과정이 필요할 것 같습니다.

6.서버의 경우는 node.js나 php를 고려해보아야할 것 같은데 이 부분은 더 공부한 후 의견 공유하도록 하겠습니다. 도메인의 경우는 나중에 생각해도 될 것 같기도 합니다..

교수님께서 말씀하신 것처럼 우선 예측데이터부터 빠르게 구현해보려고 시간을 내어 공부하며 시도하고 있습니다. 데이터 구성에 고민이 됩니다. 열심히 해보겠습니다.

그리고 위에 했던 이야기의 반복인데, 제가 이 주제를 말했을 때의 의도는 **저출산,고령화가 심각하다는 것은 안다 그러나 얼마나 심각한지 앞으로는 어떻게 될 지 저희를 포함한 국내의 사람들이 구체적으로 알지 못해서 우리가 구체적으로 예측해서 보여주자!** 이었습니당. 혹시 다르게 이해하시거나 다른 의견이 있으시다면 빠르게 말해주시면 감사하겠습니다!!!

**Comment by won-hj** [comment]
> ## 안녕하세요. 잘 읽어보았습니다. 위 내용에 대한 저의 의견입니다.

일단 말씀하시는걸 보니 제가 너무 제 입장에서만 생각해서 부족한 부분이 조금 있습니다.

> 1.우선 데이터를 어디서 가져오냐는 질문에는 공공데이터를 활용할 것인데 10년치를 활용할 생각입니다. 데이터 분석에 쓰이는 csv파일이 없어 엑셀로 직접 만들어야 할 것 같기도 합니다.
 - 어디서도 중요하지만 어떤 데이터를 쓰냐를 좀 더 묻고 싶었습니다. 이제보니 말하고 싶은 의도에는 조금 부족한 질문인 것 같습니다.
  -> 기본적으로 출/고 수치를 보여주려면 그에 대한 데이터만 필요할거에요. 그런데 _그 외에는 어떤 데이터를 사용하는게 좋을까_ 라고 묻고 싶었습니다. 공공데이터포탈에서 가져오는 것은 당연하겠지만 아무래도 거기서 무슨 데이터를 사용할 것이냐는 다른 문제니까요. 이 문제는 을중씨 의견을 듣고나서 결정해야 한다고 생각합니다. 


> 2.사용하는 대상에 관해서는 연구직 뿐만 아니라 저희같은 일반 서민들도 최근 대두되는 사회문제에 대해 구체적으로 알고 싶어 활용해보지 않을까요?
 - 그럴 수 있을 것 같아요. 아래 예시 들어주신 것처럼 충분히 이슈를 몰고다니며 활동하는 분들도 충분히 계시고 그 밖에도 관심있는 사람들이 있을 수 있으니까요. 너무 단편적으로 생각했네요. 그렇지만 그럴수록 세분화하는게 더 좋다고 생각해서 쓴 말이었던 것 같습니다. 왜냐면 실력에 비해 기간이 여유롭지는 않다고 보거든요. 2달하고 2주정도?의 산으로 추청하는데 이것저것 하다보면 여유가 있을지는 모르겠어요. 무엇보다 예측의 정확도가 중요한게 아닌 것 처럼 누구 입장에서 사용하도록 만드는 것이 반드시 의도에 맞게 사용될 필요는 없잖아요. 사용자 그룹에 제공하는 기능이 많지 않으면  두 집단 모두 고려해도 크게 문제가 있진 않겠지만 관리자와 일반 사용자 같은 경우가 아닌 이상 시간이나 다른 기타 문제들도 충분히 생길 가능성이 높다고 생각합니다.... 
 -->어떻게 전달이 잘 안될 수 있어요..... 저도 쓰면서 어떻게 써야 할지 굉장히 고민중이고 계속 수정하면서 바꾸고 있는 중인데 이렇다고 나아지는건 딱히 없어보여 일단 써넣겠습니다. 다른 이해 안되는 부분이나 그런거 있으면 알려주세요
 -> 따라서 이 문제도 사실 을중씨 의견이 필요는 하다고 봅니다. 빼놓을 수는 없으니까요.
 

> 3.어차피 비슷비슷하다는 말씀은 해석하기에 따라 받아들여지는 것이 다를 것 같은데, 저희가 주제를 정한 이유가 고령화와 저출산이 가속화되가고 있다는 것은 알지만 정확한 수치로 그리고 가시적으로 받아들이면 좋겠다였으니 구체화해서 보여준다는 것이 의미가 있을 것 같습니다.
 - 제가 의도했던 _비슷비슷_ 이라는 말은 구현방법에 대한 의미였습니다. 그러니까 출산율에 대한 결과를 보여준다고 한다면 고령화에 대한 결과도 똑같지는 않을 수 있겠지만 크게 다른 방식이 아닐 것이라는 말이었습니다. 해석하기 나름이라 더 상세히 말했어야 했네요... 죄송해요.....
 -> 출산율과 커뮤니티는 다른 기능이니 구현 방법도 다르겠지만 제가 써놓은 것처럼 인구분포라 한다면 출산율과 같은 방식으로 결과를 나타낼 것이라는 의미였습니다. 


> 4.저는 일반사용자에게도 충분히 가치있다고 느낍니다. 오히려 연구직 분들은 저희의 데이터분석이 형편없다고 안 보실지도 모르겠습니다. 예로 유x브에 x카월드라는 크리에이터가 주기적으로 저출산 문제를 다루고 있는데 조회수가 굉장히 높습니다. 일반 사용자에게도 굉장히 관심있는 주제라고 보여집니다.
 - 2번처럼 충분히 사용가능한 것 같습니다. 따로 더 쓰진 않겠습니다.


> 5.게시판의 경우 만들면 정말 좋겠지만 백엔드가 필요하고 이 부분의 경우 저도 공부를 많이해야하기에 혁주님의 말씀대로 조율해나가는 과정이 필요할 것 같습니다.
 - 6번에 대한 답에 포함되겠습니다. 6번 먼저 확정짓고 이후 추가 기능들에 대해 의논해봐요.

> 6.서버의 경우는 node.js나 php를 고려해보아야할 것 같은데 이 부분은 더 공부한 후 의견 공유하도록 하겠습니다. 도메인의 경우는 나중에 생각해도 될 것 같기도 합니다..

 -> _네 맞아요. node.js나 php를 사용할 수 있겠어요. 그런데 제가 알기로는 그런걸 사용하는 대신 프레임워크로 대체하는 것이 가능하다고 알고있어서 그 중 flask를 제안한건데 제가 이 부분에 대해 헷갈리네요... 파이썬으로 데이터를 주고 받을 구조를 만들고 웹 프레임워크를 이용해 node/php를 대신하는걸 생각한건데 어 .. 이게.. 근데 프레임워크를 안쓸거면 n/p로 구조 만드는거고 쓰면 그거로 대체하는게 아닌가 하는 중입니다......_ 
 --> 검색해보니 살짝 덜 알고 있어서 표현을 제대로 하지 못하는 것 같아요.. node.js나 php도 프레임워크가 따로 있는데다가 우리가 하는게 예측이라는 것이니까 이걸 아무래도 파이썬같은거로나 좀 하는 분야기도하기 때문에 다 써야하지 않을까 합니다..  연동을 하는거지 따로 배타적인건 아니네요............ 
---> 이 부분도 제가 표현을 잘 못하고 있는데 그래도 상의해봐야하는 부분이라고 생각합니다.


> 교수님께서 말씀하신 것처럼 우선 예측데이터부터 빠르게 구현해보려고 시간을 내어 공부하며 시도하고 있습니다. 데이터 구성에 고민이 됩니다. 열심히 해보겠습니다.
> 
> 그리고 위에 했던 이야기의 반복인데, 제가 이 주제를 말했을 때의 의도는 **저출산,고령화가 심각하다는 것은 안다 그러나 얼마나 심각한지 앞으로는 어떻게 될 지 저희를 포함한 국내의 사람들이 구체적으로 알지 못해서 우리가 구체적으로 예측해서 보여주자!** 이었습니당. 혹시 다르게 이해하시거나 다른 의견이 있으시다면 빠르게 말해주시면 감사하겠습니다!!!

-> **저출산,고령화가 심각하다는 것은 안다 그러나 얼마나 심각한지 앞으로는 어떻게 될 지 저희를 포함한 국내의 사람들이 구체적으로 알지 못해서 우리가 구체적으로 예측해서 보여주자!** 라고 하신건 정말 좋습니다. 갈수록 명확해지고 있는데요. 여기서 걱정이 조금 될 부분이라면 구체적이라는 단어에요. 교수님이라면 뭐라고 하셨을까요? 구체적이면 무엇을 얼마나 어떻게 같은 말들이 따라올텐데 아직 확정이 많이 된건 아니다보니 조금 걸리는 것 같습니다. 위에 있는 것들부터 마무리를 지으면 금방 해결될 것 같습니다.


**_무엇보다 을중씨 의견 필요하다고 생각합니다!!!!!!!!!!!!!!!!!!!!!_**

**Comment by KimEulJoong** [comment]
정리하겠습니다.

**주제: 저출산 고령화에 대한 심각성을 인지할 수 있도록 돕고 미래 전망은 어떠한지 예측하여 정보 제공 (구체화 필요)**
-> 웹 개발을 기준으로 우리가 이야기 했던 기능을 UI로 간략하게 구상해 본다면, 
메인 페이지(저출산 고령화에 대한 전반적인 미래 전망을 그래프로 표현)
![저출산 이미지](https://user-images.githubusercontent.com/127865678/229269668-72adb78a-0b0e-48ad-81e0-d80d56a4a9eb.png)
*해당 이미지는 저출산 고령화 영향을 받을 것으로 예상되는 분야 목록 예시입니다. 

**전반적인 동향을 이곳에서 포괄적으로 보여준다.**

->서브 페이지(개인 맞춤형 예측 서비스 제공: 나이 입력 시 전망을 예측해 주는 서비스) : 미래 노동시장 환경 변화를 예측해서 소비자에게 제공해줌으로서 소비자가 저출산 고령화에 대한 심각성을 현실적으로 인지하고 미래에 대한 고민과 대비를 할 수 있도록 도움
ex) 교대 대학생 23살의 10년 후 >> 저출산으로 인한 교육 분야 수요 몇퍼센트 감소, 도움이 될 수 있는 관련 자료 제공

**서브 페이지에서 추가적인 메인 기능**
커뮤니티, 위치 기반 요양시설/장례식장 및 보건소 표시 및 예약기능, 회원 포인트제 등

### 서비스를 구체화 한다면 이런식으로 구체화 할 수도 있다고 생각합니다. 개인적인 의견입니다.

**Comment by KimEulJoong** [comment]
**1. 공공데이터포탈에서 가져오는 것은 당연하겠지만 아무래도 거기서 무슨 데이터를 사용할 것이냐**
무슨 데이터를 사용할지 정하려면 우선 우리가 어떠한 정보를 사용하고 가공해서 소비자에게 어떠한 정보를 제공해 줄 것인가를 생각해 봐야겠죠. 제 개인적인 생각으로는 
1-1. 저출산 고령화에 대한 다양한 분야에서의 데이터 (ex. 현재 시도별 부양비 현황 데이터 -> 미래 시도별 부양비 현황 예측 데이터)
1-2. 소비자에게 도움이 될 만한 관련 데이터 (ex. 교육 분야를 중점으로 한다면 미래 학교가 얼마나 줄어드는지, 학생은 얼마나 줄고 교직원 수요가 얼마나 줄어들지, 시도별 학교 분포도 순위 데이터 등)
1-3. 위치 기반 요양시설/장례식장 및 보건소 표시 및 예약기능을 추가한다면 요양시설과 장례식장등의 위치 데이터도 수집해야겠죠.
등등

**2. 소비자 대상 선정 기준**
소비자 대상은 비전문가(일반인)으로 선정하는 것이 좋다고 생각합니다. 
개인맞춤 예측 서비스를 제공해준다는 것은 저출산 고령화와 같은 막연하고 가시적으로 확인하기 힘든 문제에 대해서 시민들이 본인의 경험과 사례를 바탕으로 본인의 미래 동향을 생각해볼 수 있다는 것이지요. 이러한 점은 저출산 고령화 문제에 대한 인식 개선을 도울 수 있다는 장점이 분명 존재한다고 생각합니다. 또한 도움이 될 수 있는 관련 정보를 제공해 줄 것이기 때문에 충분히 서비스로서의 메리트가 존재하지 않을까요.

**3. 프로젝트 진행을 위해 사용할 도구**
-웹-
프레임워크(파이썬 기반): 플라스크, 장고
프레임워크(자바스크립트 기반): 리액트
백엔드-데이터베이스 : SQL
           - 프레임워크 : Express 
           - 플렛폼 : Node.js
-앱-
코틀린(자바스크립트 기반), 플러터(C기반)

저도 마찬가지로 무엇을 시도하고 어떠한 도구를 사용하든 경험이 없기 때문에 배워가면서 해야하는 건 마찬가지로 똑같고 그런 의미에서 어떠한 도구를 사용하여 앱이나 웹을 구현하는가는 큰 상관없이 다 괜찮습니다. 

앞서 도현씨가 말씀해주신 것 처럼 백엔드 개발 시 데이터베이스만 SQL을 사용하고 Node.js나 Express와 같은 프레임워크 플렛폼을 사용하지 않고 플라스크를 통해 일괄 처리가 다 가능한 것으로 알고있습니다.  장고도 마찬가지이구요. 
따라서, 장고나 플라스크 + html + SQL 을 이용하면 서버와 웹 페이지 개발까지 다 가능해보입니다. 주로 사용할 언어는 파이썬이 되겠네요

적다 보니까 서비스 구체화가 좀 더 필요해보이네요. 제가 말한 것들을 전부 하려면 정말 다양하고 많은 데이터를 수집하고 가공해야하는데 현실적으로 힘들어 보여요. 
대안1. 메인 페이지에 들어갈 전반적인 미래 저출산 고령화 동향 예측 데이터 제공 삭제 
           서브 페이지에 들어갈 개인 맞춤현 서비스를 메인 서비스로 제공 
대안2. 분야를 명확하게 정해버리기 (ex. 보건/ 부동산/ 교육 등)

**Comment by dozzzang** [comment]
말씀하신 부분들 고려해 보았습니다.
무슨 데이터를 가져올 것이냐에 대한 저의 의견입니다.
우선 보여주고 싶은 것은 일반 서민들이 가장 궁금해할만한 부분을 생각해보았습니다.
**1.전체인구수 2.생산가능인구 3.생산불가능인구**
그에 따라 가져올 데이터를 구상해보았습니다.
**2013~2020년 data 1.전체인구수 2.출산율 3.사망률**
국제이동률은 고려하지 않는다.

어떻게 예측할 것인지 구상해보았습니다.
**8개년 data를 활용하여 출산율을 예측 (50%), 사망률을 예측(기술의 발달로 기대수명이 늘어날 것으로 판단되어 25%)**

이후, 출산율 - 사망률을 계산한 값을 전년도 전체인구수에 곱하여 미래 인구수 예측
이것이 보여주고 싶은 것중 1번에 해당할 것입니다.

문제는 생산가능인구 (15세부터64세), 생산불가능인구(15세부터64세)인데 공공데이터가 존재하긴 하나 연도별로 묶여있는 것이 아니라 데이터 가공 및 정제 과정이 필요할 것 같습니다. 위의 예측결과와 종속적으로 예측해야할 것 같은데 (독립적으로 예측했다가 취합했을 때 값이 다르게 나올 것 같아서) 이는 해봐야 할 것 같습니다.

따라서 우선사항으로 보여주고 싶은 것 중 1번에 해당하는 것을 빠르게 작업하려고 하고 있고(4월 9일까지는 반드시) 2번 3번은 아직 시간이 많으니 천천히 구상해볼 예정입니다. 지역별 인구 수도 할 수 있다면 정말 좋겠으나.. 지역을 도로 나누어도 항목들이 너무 많아져 저희 레벨에서 예측을 시도했을 때 값이 많이 튈 것 같고 복잡할 것 같습니다.. 따라서 우선은 고려하고 싶지 않습니다.

다른 의견 있으면 부탁드립니다. 아 그리고 이에 따라 제가 데이터분석을 맡고 싶습니다. 만약 1,2,3번까지 다 구상하게 되면 도와주는 방식으로 하고 싶은데, 다른 기능들을 구현하려면 데이터분석한 내용들이 반드시 필요할까요?

**Comment by dozzzang** [comment]
사실 통계청에 시나리오별(ex.출산율 유지,사망률 유지,국제이동률 유지)로 예측한 결과값이 2070년까지 이미 존재합니다. 하지만 이는 2020년을 기준으로하였기 때문에, 정확하지 않다고 판단하고 그래프나 표로 나타낸 것이 없었습니다. 따라서 더 많은 데이터를 사용한다는 점, 접근하기 쉽게 그리고 더 가시적으로 표현할 수 있다는 점에서 차별화를 두고 싶습니다. 저희가 계속 말했던 것처럼 얼마나 정확하게 예측하냐는 문제는 주요한 문제점이 아니니깐요.

그리고 단순히 전체인구수 생산 가능 인구수 생산불가능 인구 수를 예측하는 것이 저출산 고령화와 무슨 관련이 있느냐??라고 혹시 생각하실 수도 있을 것 같아 그것에 대한 제 생각인데 위 3가지를 예측하는 것이 곧 저출산 고령화를 보여줄 것이기 때문에 그게 그거다라고 말씀드리고 싶습니다! 혹시나 해서 적어봤습니다.

**Comment by won-hj** [comment]
지금 올려주신 것을 다 보았습니다.
점점 구체화되고 있다는 느낌이 듭니다 !!
 
지금까지의 의견을 종합해보자면

1. 주제 
 - 저출산/고령화로 인한 변화에 대한 개인 맞춤 정보 제공 서비스
   >저출산 고령화에 대한 심각성을 인지할 수 있도록 돕고 미래 전망은 어떠한지 예측하여 정보 제공 
           ->  _**심각성 인지를 돕는 다는 부분**_ 은 주제보다는 목적...에 가까운 것 같습니다 !!!!!!!!!! _**미래 전망은 어떠한지 예측하여 정보 제공**_ 의 경우 개인 맞춤 정보로 통합했습니다.

2. 목적
 - 일반 사용자를 대상으로 저출산 고령화와 같은 막연하고 가시적으로 확인하기 힘든 문제에 대해서 시민들이 본인의 경험과 사례를 바탕으로 본인의 미래 동향을 생각해볼 기회 제공

3. 기능
 - I. 저출산/고령화 추이 그래프
   > I.a 전체인구수/ 생산가능인구/ 생산불가능인구 에 대한 전체인구수/출산율/사망률 그래프
- II. 소비자에게 도움이 되는 데이터 제공 기능
   > II.a 시도별 부양비 현황 데이터(현재->미래)
   > II.b 학령인구 및 교육시설 수 변화 예측 그래프 
   > II.c 고령화 관련 기반시설 제공 기능
   > II.d 현재 나이(와 추가정보; 전공 등) 기반 미래 예측 결과 및 관련 정보 제공 _교대 대학생 23살의 10년 후 >> 저출산으로 인한 교육 분야 수요 몇퍼센트 감소, 도움이 될 수 있는 관련 자료 제공_
   >등
 - III. 커뮤니티 기능
   > III.a 커뮤니티
   > III.b 회원 포인트제 
   > 등

4. 개발도구
- 개발언어 : 파이썬, (javascript, html, css)
- 동적웹프레임워크: flask 혹은 django 
-  
5. 개발 환경
 - IDE : 뭐로할까요~~~~ vs code/ jupyter/ pycharm/ intellij 등등....
 - 데이터베이스 : 일반 데이터를 저장할 Oracle/ mysql/ mariaDB/ postgreSQL 등등 중 하나 선택, 예측을 위한... 이 부분은 [기사](https://www.itworld.co.kr/news/270663) 로 대체하겠습니다. 
 - 운영체제 : Windows/ macOS 
 -
정도로 생각해 볼 수 있습니다.
틀린 부분이나 빠진 부분 등 수정해야하는 곳이 있으면 알려주세요!!

또한 을중씨 해주신 화면 예시 정말 좋은 것 같습니다. 하지만 화면은 결정을 한 후 수정이 또 되어야 하기 때문에 위에 올려주신 표와 내용을 추후 수정해나가면 될 것 같습니다!

아까 쓰려고 했던 내용이 있었었는데 지금 갑자기 생각이 나지 않습니다.. 내일 밤에 돌아오면 다시 보고 수정하거나 추가하겠습니다...

**Comment by KimEulJoong** [comment]
IDE고민하다가 생각났는데 우리가 만들고자 하는 것은 서버가 따로 필요 없어서 데이터베이스도 고민할 필요 없다고 생각합니다. 데이터 활용은 이런 느낌으로 해도 되지 않을까요. 참고만 하세용(https://dvlp-jun.tistory.com/2)

IDE는 개인적으로 vscode가 좋지 않을까 생각합니다. 오늘 작년 오픈소스기초프로젝트 수강생한테 물어봤었는데 그 팀도 vscode로 웹 형태 구현까지 한번에 다 했더라구요. 편하다고 합니다. 내부에서 주피터도 지원해주는 것으로 기억합니다. 

작년 오픈소스기초프로젝트 수강생들 보면 방금 언급했던 것과 같이 vscode로 웹 형태 구현까지 다 한 팀도 있고, 웹 프레임워크 사용한 팀도 있었습니다. 웹 프레임워크 사용한 팀은 이캠퍼스 자료실에 올라와 있던 링크 참조하시면 될것같습니다. 이 팀은 django 사용했네요.( https://github.com/AhnYeonghoo/opensource_project )

좀더 조사해보고 저녁에 다시 올께요

**Comment by won-hj** [comment]
올려주신글과 링크(블로그, 수강생)도 다 봤습니다!!!!
블로그의 경우 우리가 할 것과 굉장히 유사한 면이 있어요
미세먼지라는 주제가 다르기 때문에 제공하는 기능이 그만큼 같지 않은 정도고
똑같이 어느 정도 학부생 수준에서의 데이터 가공과 예측의 내용인 것 같습니다.


저는 말씀하신 데이터베이스도 고민할 필요 없다고 하신 점을 사용할 필요가 없다는 것으로 받아들이고 있어서 현재 '있어야하는게아닌가' 고민하고 있는 상태입니다.
도현씨가 하고싶다고 하는 데이터분석에 대해서는 블로그와 같이 데이터베이스가 직접적으로 필요는 하진 않을 것이지만 그 데이터를 어디에 저장하고 다음에 불러올 수 있어야 한다는 생각을 합니다.
당장 다운받은 데이터들을 정제하는 과정 자체에서는 필요하지 않아도, 정제된 데이터들을 보관할 필요는 있지 않을까 싶습니다.
그래서 시스템(이라고한다면)에 접속할 때 데이터베이스에 저장된 내용을 보여주는 식인 것이죠.
그런데 그냥 api에서 바로바로 보여주기만 하는 방식이라면 저장할 필요까지도 없긴 하겠어요...
이걸 의미하는 것 같기도 하네요!!
근데 그렇다고해도 커뮤니티기능이라던지 이런 기능들을 만들려면 필요하다고는 생각합니다.

말씀해주신 것들 계속 생각하며 글을 써보니 우리가 만들 서비스에 대한 구조가 아직 명확하지 않은 것 같습니다.
내일 수업도 4시간씩 있고 잠깐이라도 상의를 하고 정리하는 시간을 가지면 좋을 것 같습니다.
또한 무엇보다 환경을 설정하는건 주제가 확정되지 않아도 공통된거니 최대한 빨리 시작하는 것도 괜찮다고 생각합니다.

일단 내일 봅시다~
