### ISSUE TITLE
docstring 주석 양식

### ISSUE THREAD

**Issue by dozzzang** [won-hj/mon2tor#31]
docstring으로 따로 문서화하기 전에 python 코드에 주석을 남기는 것은 return type만 명시하는 것을 지향하라고 하셨고,
docstring으로 문서화할 때 인자(arguments),return type,함수 설명을 기재하라는 것 맞았나요?
8주차 강의자료를 다시봐도 이에 대해 자세한 구분이 없어 헷갈리네요.

**Comment by won-hj** [comment]
제가 보기에도 그냥 어떤 함수인지, 무슨 인자를 가지고 무슨 반환값을 주는지 명확한 설명을 구문으로 기재하라는 것으로만 같아요!!
