### ISSUE TITLE
웹 화면은 모두 사용하는건가요?

### ISSUE THREAD

**Issue by won-hj** [won-hj/mon2tor#33]
커밋 메시지 보니까 아직 미완료라고 되어있는데 웹 디렉토리 아래에 있는 html 전부 사용하는게 맞나요?

그리고 template에 html, static에 js나 css같은걸 넣어야하는데 구조 변경시 문제 없죠? 

아직 완성이 안되었고 다 사용한다기엔 인덱스페이지만 있어도 될 것 같은 느낌이라 어떻게 해야할지 모르겠어요!!

**Comment by KimEulJoong** [comment]
제가 이번 주 주중으로 웹 페이지 완료해서 업데이트하도록 하겠습니다. 웹 디렉토리 아래에 있는 html을 전부 사용해도 좋지만 필요 없을 시 지우면 되므로 문제없습니다. index페이지만 있어도 될 것 같은 느낌이라는 말 이해했습니다. 우선 우리가 사전에 이야기했던 형태로 메인페이지 형태가 나올 수 있도록 수정하여 업데이트하겠습니다.

**Comment by won-hj** [comment]
넵 알겠습니당
