### ISSUE TITLE
향후 목표 및 이슈

### ISSUE THREAD

**Issue by won-hj** [won-hj/mon2tor#34]
지금 전에 했던 부분에서 문제가 있던걸 어떻게 해결해야할지 고민중이긴한데
빠른 시일 안으로 해결이 안된다면 더더더더 간단히 하는 쪽으로 하겠습니다.

그리고 지금 웹쪽을 어떻게 사용하면 좋을지 아직 모르는 상황이라 뭔갈 할 수 있지 못할거같고
그래프 표현하는거까지는 임의로여도 해보겠습니다...

브랜치 슬슬 바꿔야할거같은데 feature_drawgraph로 할거같아요

또 지금 또 문제가 뭘 하겠다고 생각을 해놓고 다른걸 보면 잊어버려서 조금 문제인 상황인데 
일단 계속 생각하고 적어가면서 체크해야겠습니다 
최대한 빨리 잘 해보겠습니다

**Comment by dozzzang** [comment]
네~ 아직 html쪽 코드리뷰를 못해봤는데 예측 그래프 다 생성하고 코드리뷰 해보겠습니다.
