### ISSUE TITLE
새로운 이슈

### ISSUE THREAD

**Issue by won-hj** [won-hj/mon2tor#35]
커밋하기 전까지 그래프 여러개(2013 ~ 2022) 화면에 띄웠었었는데
커밋하고 푸쉬하고나니 있지도 않은 2013data.csv가 없다며 오류가 생겼습니다

알고보니 tool 디렉토리에 first_data와 second_data가 추가되어 생긴 문제인데
이름 통일하던지 지우던지 바꾸던지 해야할 것 같습니다

두개 빼고 실행해보면 가로로(옵션 설정 안했으니까) 주르륵 나옵니다 

확인 한번 해보세요

**Comment by dozzzang** [comment]
tool에 first_data와 second_data가 추가되어 2013data.csv가 없다고 푸쉬하는 과정에서 에러가 났다는 말씀이죠?

**Comment by won-hj** [comment]
두 파일이 추가되어 그래프 표현이 안되는 것입니다
푸쉬 후 확인한 문제입니다

**Comment by dozzzang** [comment]
파일이 추가되었지만 그 파일이 코드에 영향을 주었나요? 왜 그래프 표현이 안된다는 것인지에 대한 이유를 잘 모르겠어서요.

**Comment by won-hj** [comment]
디렉토리에서 파일개수나 파일명을 조회하는데
경로+2013+i(0~n)+기타문자열 의 형식으로 불러와서 그렇습니다
tool 디렉터리에 CSV파일(뭔진 모르지만 있어서 고려하고 -1했습니다) 까지 개수를 세어 
../tool/ + 2013 + i + data.csv 로 13년부너 22년도까지 조회를 합니다
first second는 저 규칙에 부합하지 않아서 그래요!

**Comment by dozzzang** [comment]
아~ 그렇다면 어떻게 바꿔주면 될까요?

**Comment by won-hj** [comment]
파일 이름만 규칙성있게 만들면 되는거라 최종적으로 바꿔도 문제는 없어요
대신 보니까 1년에 1개씩이 아닌거같던데 이런 부분에서 어떻게 할건지는 알아야 나중에 고치기 쉬울거같아요
어차피 보케쓰는건 거기서 거기잖아요 
그러니까 몇년 단위 파일을 만들어사용할거고 이름은 어떻게 하고 싶은지만 알면 될거같습니다

**Comment by dozzzang** [comment]
사실 DB를 만들어서 관리했어야 하는데 하나하나 CSV파일로 관리하려니 이런 문제가 발생한 것 같네요.
지금 tool 폴더에 있는 first_data.csv는 2023-2027 예측용도 과거 데이터 csv이고
second_data.csv는 2028-2032 예측용도 과거 데이터 csv입니다.
2023-2027.csv
2028-2032.csv
로 변경하면 될까요?

**Comment by won-hj** [comment]
날짜만 구분할 수 있으면 문젠 없긴합니다...
근데 13년도부터 22년도까지는 따로따로 관리하면서
23년도부터 5년단위를 하나의 파일로 관리한다면 예측용도 파일만 따로 구분해야 할 필요가 있겠네요......
tool 아래에 과거와 미래 데이터를 구분하는 디렉토리를 만드는 것은 어떨까요?

또 과거는 그럼 10개? 를 보여주고 미래는 5년단위로 2개만 보여주는게 맞나요?


아 그리고 datapipeline이라는 폴더가 있는데 이건 무슨 용도인가요? 
그리고 tool에 지금은 first와 second를 없앤 상태로 보이지만 CSV는 무슨 용도인지 아시나요??
별 의미가 없으면 지우는게 좋을듯싶어요

**Comment by dozzzang** [comment]
> 날짜만 구분할 수 있으면 문젠 없긴합니다... 근데 13년도부터 22년도까지는 따로따로 관리하면서 23년도부터 5년단위를 하나의 파일로 관리한다면 예측용도 파일만 따로 구분해야 할 필요가 있겠네요...... tool 아래에 과거와 미래 데이터를 구분하는 디렉토리를 만드는 것은 어떨까요?
> **네 그렇게 할게요**
> 또 과거는 그럼 10개? 를 보여주고 미래는 5년단위로 2개만 보여주는게 맞나요?
> **네 15년까지 예측이 가능하면 그렇게 하겠습니다**
> 아 그리고 datapipeline이라는 폴더가 있는데 이건 무슨 용도인가요? 그리고 tool에 지금은 first와 second를 없앤 상태로 보이지만 CSV는 무슨 용도인지 아시나요?? 별 의미가 없으면 지우는게 좋을듯싶어요
>만약 데이터가 더 추가되면 손쉽게 추가할 수 있게 데이터파이프라인을 구성하고 있어요. 시간이 나면 sql을 이용해서 db화 시키려고 했는데 브랜치가 꼬여버리는 바람에 시간이 안 날거 같네요. 지금 first와 second를 없앤 상태로 보이나요? 저는 continuous_data 브랜치에 있습니다. 네 그리고 csv는 지우겠습니다.
