### ISSUE TITLE
reset 소요

### ISSUE THREAD

**Issue by dozzzang** [won-hj/mon2tor#36]
![image](https://github.com/won-hj/mon2tor/assets/74997120/6539c7fd-83f9-4037-8413-5dc0791f5bf2)

Netword 그래프를 보시면 갑자기 main으로 커밋이 뻗어나가는 것을 오늘 오전에야 확인했습니다.
git log를 들어다보며 원인을 분석해보니 제가 로컬 main 브랜치에 remote main을 pull받고, 또 로컬 브랜치에 remote main을 pull 받아 처음 pull받은 main에서 작업한 것으로 인지된 것 같습니다.

따라서 이 문제를 해결하기 위해 로컬 main 브랜치에 remote main을 merge받은 시점 이전으로 revert해야할 것 같은데, 이미 오늘 새벽에 제 브랜치를 pull받으셨더군요. 만약 제가 revert를 하게 된다면 혁주님이 merge받은 시점과 차이가 날 수 있을 것 같은데 이 경우 혁주님의 merge받은 시점도 revert해야할까요?

**Comment by won-hj** [comment]
push 하기 전에 pull 하라고해서 했던건데 이런 문제가 있었나보네요 
근데 먼저 revert 한 후 상황을 봐도 괜찮을거같아요
시점 차이 난다고 해봐야 정상 브랜치에서 pull해오면 고쳐지지 않나 싶습니다
안되면 저도 revert하면 되는거니까 급한거면 일단 해봐도 문제 없을것같습니다

**Comment by dozzzang** [comment]
교수님께 여쭤본 결과,
pull 받은 이전의 시점으로 돌리는 방법은 reset을 사용하는 것이었습니다.
![팀프로젝트 reset 결과 1](https://github.com/won-hj/mon2tor/assets/74997120/d8f19cde-b591-4f53-8891-b3fd1c9fb8b6)
처음 reset 후 사진입니다. prediction_graph branch가 여전히 해결되지 않았습니다. 
reset을 다시 prediction_graph branch에서 저 커밋을 푸쉬하기 전으로 되돌리니 
![image](https://github.com/won-hj/mon2tor/assets/74997120/3b38d73e-4841-4f54-9e46-59b5b55b976f)
와 같은 상태가 되었습니다. 
더 이상은 건드릴 엄두가 나지 않아, 냅두고 우선은 프로젝트 완성에 집중해야겠습니다.
사실, 
![image](https://github.com/won-hj/mon2tor/assets/74997120/ae16d313-9864-4fa6-aaa0-430843dfd317)
이 혁주님이 merge받고 왜 
![image](https://github.com/won-hj/mon2tor/assets/74997120/fe3f33be-cd7c-43df-986a-9facbc3a607d)
다음과 같이 된 지 문제를 파악하는 것이 우선이었다고 생각합니다.

팀 프로젝트인만큼 저 때문에 이전 작업들이 꼬이게 된 것 같아 팀 분들에게 정말 죄송하게 생각합니다.
