### ISSUE TITLE
환경변수같은거 만들겠습니다

### ISSUE THREAD

**Issue by won-hj** [won-hj/mon2tor#37]
feature_envset 이라고 하겠습니다
수업시간에 했던 그 환경변수들 중 얼마나 만들면 좋을지 모르겠지만
pycache랑 경로명이랑 보고 더 추가할 것 같습니다

**Comment by won-hj** [comment]
vscode에서는 파일이 없다던지 이런 문제가 있었어서
putty 에서 해보려 했는데 
flaskRouting 브랜치를 머지한게 아니어서 클론떠도 적용이 안되어있네요
그리고 132.~~~로 접속해도 제대로 뜨지 않습니다..... 
다른 방법을 찾아보겠습니다

**Comment by won-hj** [comment]
처음 생각했던 것은 .bashrc나 config 파일 같은 것들인데
bashrc같은 경우 vscode는 gitbash를 쓴다고 해도 적용되는 것이 아닌 것으로 체감되고
config같은 경우도 경로같은 것을 한꺼번에 처리하려 했지만 선뜻 손대기 망설여지네요...
config 내용에 어떤 것이 들어가면 좋을지 생각 있으시면 알려주세요

gitignore는 의외로 .gitignore 파일 만들고 안에 __pycache__같이 써놓으면 적용이 되더라구요
근데 여기 더 들어갈만한 내용이라던지 그런게 더 있을까요?
또 gitignore도 커밋해야 하겠죠? 아무래도??

**Comment by dozzzang** [comment]
> 처음 생각했던 것은 .bashrc나 config 파일 같은 것들인데 bashrc같은 경우 vscode는 gitbash를 쓴다고 해도 적용되는 것이 아닌 것으로 체감되고 config같은 경우도 경로같은 것을 한꺼번에 처리하려 했지만 선뜻 손대기 망설여지네요... config 내용에 어떤 것이 들어가면 좋을지 생각 있으시면 알려주세요
> 
> gitignore는 의외로 .gitignore 파일 만들고 안에 __pycache__같이 써놓으면 적용이 되더라구요 근데 여기 더 들어갈만한 내용이라던지 그런게 더 있을까요? 또 gitignore도 커밋해야 하겠죠? 아무래도??

네 gitignore은 필요 시 커밋하고 푸쉬하면 좋죠 ignore 할 게 있으면 계속 수정해나가면 될 거 같아요.

https://emilkwak.github.io/python-setting-file-ext
이 링크를 참고해서 살펴보면 저희한텐 csv파일이 tool이 아니라 config에 위치해야할 것 같은데 어떻게 생각하시나요?

**Comment by won-hj** [comment]
yaml 이 적절해 보기인한데
구조를 어떻게 만들어야할지는 바로 생각이 나진 않네요.......

**Comment by dozzzang** [comment]
제가 처음부터 데이터베이스화를 했어야하는데 무식하게 csv로 다 하다보니 이런 문제가 발생한 것 같네요. 우선은 다른 형식으로 변경하기보다는 csv를 사용하고 tool폴더명을 config로 바꾸면 될 것 같아요.
시간이 남는다면 db화 시도도 해보겠습니다

**Comment by won-hj** [comment]
그럼 tool을 config로 바꾸고 

db는 환경설정만 잘 하면 큰 문제는 없을듯싶은데 
고려를 한다면 어떤걸 쓸건지랑 버전 정도? 필요할 것 같아요

**Comment by won-hj** [comment]
일단 .gitignore에는 pycache만 추가하면 될거같고 

tool -> config 변경 후 
printgraph도 config에 이동시키는게 맞는 것 같습니다

아니면 .config 파일에 경로명 같은거만 따로 배치시키고 src에 두는 것도 방법 같습니다
이 경우 configparser라는게 있네요 이거 보고 잘 써보면 될듯합니다

**Comment by dozzzang** [comment]
네 인지하겠습니다~

**Comment by KimEulJoong** [comment]
확인하였습니다
