### ISSUE TITLE
시스템 구조 생각해보면 좋겠습니다.

### ISSUE THREAD

**Issue by won-hj** [won-hj/mon2tor#4]
![image](https://user-images.githubusercontent.com/128560356/230430524-8bf89a3d-30c0-48d0-b31b-9f87d9853ddf.png)

간단하게 3가지로 구분했어요
1. 서버에서 데이터만 보여주는 식입니다. 따로 데이터베이스를 쓰진 않기 때문에 로그인이나 커뮤니티 등 기타 기능은 제공하지 않습니다.
2. 데이터베이스를 만들어두는 것입니다. 커뮤니티같은 용도로만 사용하게끔 가공할 데이터와 배타적입니다.
3. 출산율/고령화 관련 데이터도 데이터베이스에 저장하여 사용하는 것입니다. 대신 무겁습니다.

첫번째 이슈에서 말씀하신 것과 수업시간에 도현씨가 하신 말씀을 보면 1번으로써 출산율과 고령화와 관련된 시각적 기능만 제공하는 것으로 생각하고 있습니다.
기간을 생각하면 많은 기능을 구현하지 못할 것이라고 여겨지기 때문입니다.
추후 상황에 따라 추가적인 행동을 하는 것입니다.
대신 나중에 기능을 새로 만드는데 필요한게 있어 설치하고 연동해야 한다면 더욱 복잡해질 수 있습니다.

또 고민중인 것은 어떻게 시작하냐 입니다.
1. 웹 화면만 먼저 구현한 후 웹서버를 만든다.
2. 서버부터 만들고 웹은 그 다음부터 만든다.
3. 동시에 만든다 
다 장단점이 있는데 1번을 한다면 정제한 데이터를 먼저 시각화 할 수 있을 것입니다.
2번은 1과 비슷할 것이라고 생각합니다.
3번은 살짝 속도가 느리지만 동시에 하는 만큼 완성도 동시에 할 가능성이 높습니다.

그리고 프레임워크 같은 것을 어떻게 적용시키냐가 문제입니다. 이 부분은 더 찾아보고 최대한 빨리 시작해보겠습니다.

서버도 그냥 통째로 하나만 만들어서 쉽게쉽게 합시다........

**Comment by dozzzang** [comment]
prototype을 만들어서 웹으로 보여드릴려고 했는데 로컬에선 잘 되는데, 배포에서 에러가 나네요. 어제 저녁부터 몇 시간을 쓴건지..
결국 해결하지 못해서 사진으로 대체하겠습니다. 밑 사진들은 모두 하나의 웹 화면입니다.
![image](https://user-images.githubusercontent.com/74997120/230699494-4b9c1998-bb3b-45d4-9029-fb5289ac8176.png)
![image](https://user-images.githubusercontent.com/74997120/230699571-047232b6-eac9-4d01-bc2f-e15bbf9cf19a.png)
![image](https://user-images.githubusercontent.com/74997120/230699584-758e4b4d-5a81-492a-a555-82d1d275f2af.png)

ui는 당연히 손봐야할 것이고 flask를 이용하면 제가 화면에 나타낸 것들 다 구현가능하다고 나오더라고요.
사진에서 그래프는 정적이지만 사실 동적입니다. user가 마음대로 조작해볼 수 있어요.
기타 피드백 부탁드립니다.

db관련은 제가 무지해서 뭐라 답을 해드릴 수가 없을 것 같고, 시작의 순서는 1->2가 나을 거 같네요.

**Comment by won-hj** [comment]
putty상에서 어떻게 해야할지 잘 모르곘네요 
혹시 ide같은 도구들을 어떻게 써야할지 아이디어 있으시면 알려주세용...

연동해서 사용해보려곤 했는데 그래서 이걸 putty랑 github이랑 어떻게 사용해야할지는 잘 모르겠는 상황입니다...
아니면 정말 하나하나 putty안에서 디렉터리랑 vi로 하나하나 해서 할 수도 있긴 하겠는데......

**Comment by won-hj** [comment]
전체적인 내용은 프로토타입으로 표현하자면 저렇게 나온다라는 것은 잘 알겠습니다.
어차피 예측해서 표현해주는 것은 데이터베이스를 딱히 사용하지 않아도 충분히 가능은 하기 때문에
1번방법으로 우선 구현하고
그 다음에 기타 기능을 구현할 때나 데이터베이스같은걸 더 추가하자는 것으로 알고있겠습니다.
어차피 예측하는거랑 웹서버를 제외한 기타 서버들이랑은 배타적일 것이니까요...

**Comment by dozzzang** [comment]
네 알겠습니다.
전 putty는 리눅스 최적화로 알고 있어서 안써봐서 조언을 못 드릴거 같고
어떤 언어를 사용하시나요? 파이썬인 경우 주피터노트북,vscode가 있습니다.

**Comment by won-hj** [comment]
파이썬으로 알고 알고 있었는데 아니었나용??
플라스크가 파이썬을 쓸거에요

근데 음....
지금 제가 겪고 있는 문제가 그래서 putty를 통해 github에 연동이 될텐데 
vscode 연동하는 것도 뭔가 아닌 느낌이 너무 들어서 이것도 잘 알지 못하고 있는 상황이고...
그냥 putty로만 해볼까 해서 몇가지 간단하게 해봤는데도 원격으로 하다보니 서버를 실행해서
helloworld 띄우는 것도 로컬에서 확인을 못하는 상황이면서
또 push pull 이런것도 제대로 안되는 상황입니다..........................
지금 어떻게 해야할지 잘 모르겠네요...

**Comment by dozzzang** [comment]
아 Flask에 관한 얘기셨군요. Flask 설치는 완료하셨나요?

**Comment by won-hj** [comment]
넵 설치는 명령어 한줄이면 됩니다.
근데 로컬에서 실행할 때는 정상적으로 작동하는데
putty에서 실행하다보니 원격이라 그런지 안됩니당..,
