### ISSUE TITLE
생산 가능 인구(15세-64세)와 생산 불가능 인구(65세 이상) 예측에 대하여

### ISSUE THREAD

**Issue by dozzzang** [won-hj/mon2tor#41]
본래 출생아 수와 사망자 수 예측 데이터를 이용하여 그 출생아 수가 15년이 지났을 때 15세가 될 것이고
사망자 수와 종합적으로 엮어 데이터를 예측하려고 했었는데, 아무리 해도 안되네요.
우선, prophet으로 예측한 후 우선순위가 급한 것들부터 처리하고 재개선 시도 해보겠습니다.
예측이 주제인만큼 예측의 정확성을 올려보고 싶은데 쉽지 않네요.

**Comment by dozzzang** [comment]
생산 가능 인구와 생산 불가능 인구를 예측하는 데 있어서 출생아 수와 사망자 수는 최대한 보수적으로 수행했다면, 이 경우에는 change_prior_scale 값을 조정하여 생산 인구는 점차 진보적으로 감소하게끔 사망자 수는 점차 보수적으로 증가하게끔 하였습니다.
이것이 직접 다른 외부변수(의료산업의 발달,출생아 수 감소 등)을 고려하여 예측하는 것보다는 부정확할지라도 우리는 의료산업의 발달로 사망자 수가 보수적으로 증가할 것을, 출생아 수의 감소로 생산 인구가 진보적으로 감소할 것을 알고 있기 때문에, 이렇게라도 조정해보았습니다.

**Comment by KimEulJoong** [comment]
알겠습니다.
