### ISSUE TITLE
bootstrap_test branch에 커밋한 것들에 대한 질문

### ISSUE THREAD

**Issue by dozzzang** [won-hj/mon2tor#46]
bootstrap_test branch에 있는 커밋 내역들을 모두 확인해보았습니다.
부트스트랩을 사용하여 웹 사이트를 구현하는 것은 인지하였으나, 필요한 것만 끌어다 써야할 것 같은데 저는 도저히 엄두가 나질 않네요
코드가 주석이 없이 너무 길고 어떻게 수정해야할 지 감이 안잡혀서요.
종료까지 2주 남은 시점에서 을중씨가 수정할 수 있다면 방향을 제시해주면 저도 같이 노력해보겠습니다.
만약 그것이 아니라면, 저 코드를 수정하는 것보다 새로 만드는 것이 더 나을 것 같습니다.
다들 어떻게 생각하는 지 궁금합니다.

**Comment by won-hj** [comment]
제가 6월 9일 시험이 하나 있어서 빨리빨리 완성하면 좋을것같습니다!!!!!!!
시험날짜를 좀 전에 공지해주셔서 이제야 알게 되어버렸습니다


일단 지금 생각하는건 웹을 할 수 있으면 화요일
못해도 목요일까지는 완성시켜야 지금 뭘 연결하던지 추가를 하던지 이것저것 할 수 있을거가타용!!!!!!!!!
@KimEulJoong

**Comment by KimEulJoong** [comment]
확인했습니다. 오늘 내일로 해서 혁주씨랑 도현씨가 피드백 해주신 대로 필요 없는 페이지 전부 삭제하고, 간결하게 최대한 빨리 완성하여 올리도록 하겠습니다. 수요일까지 완성하겠습니다. 주석도 최대한 달아서 알아보기 편할 수 있도록 최대한 해보겠습니다.
