### ISSUE TITLE
경로 제가 적당히 바꾸겠습니다 PR먼저 할게요 

### ISSUE THREAD

**Issue by won-hj** [won-hj/mon2tor#48]
어차피 &랑 공백이나 이런거 지우고
보기 편하게 할게용..,,

**Comment by dozzzang** [comment]
하나 바꾸면 다 바꿔야하는데 혹시 그렇게 하셨나요?

**Comment by won-hj** [comment]
하나하나 다 바꿔야하긴 하는데 어차피 할거면 하는게 맞다고 봐요 ,,,,
이게 뭐 하나 바꾸게 되면 전체를 바꿔야하기 때문에 아얘 변수로 관리해야할거같고
이래서 config 쓰려 했던건데 이건 잘 되면 좋고 안되면 다른 방법 써야할거같아요
경로야 어차피 하나 호환되면 다른것도 큰 문제 없이 될 확률이 높겠고 디버그야 하면 되는거니까 
오히려 늦게 해서 더 문제라고 생각합니다

이건 동적 정적 하는 그겁니다..
