### ISSUE TITLE
commit pull push같은거 잘 되나요? 

### ISSUE THREAD

**Issue by won-hj** [won-hj/mon2tor#5]
간단한거 몇개 해보는데도 수업때같이 동작하지 않네요...

**Comment by won-hj** [comment]
수업 때 쓰는 리포지토리로 해보니까 
 git push --set-upstream 이거 해야할거같은데
이게 수업때는 없었던거로 기억해요
근데 집에서 하려니 저거 안하면 안되더라구요 

git push --set-upstream origin feature_branchTest

이게 돼야 브랜치들이 추가되는거같은데 
제가 잘 몰라서 검색을 해도 뭐가 어떻게 되는지 잘 모르는 상태입니다.

git pull --set 어쩌고저쩌고도 같이 나오긴 하는데
제 상태에서는 저 push만 되는 것 같습니다....

그리고 feature도 통일을 시키는게 좋을 것 같습니다.
이거 수업자료에 나온 것처럼 하는게 좋다고는 하는데 교수님 말씀하신건 또 어떻게 되는지 기억이 잘 나지 않습니다...

어차피 푸쉬야 내일 해도 내용은 남아 있는거니 지금 당장은 하진 않겠습니다.

**지금 교수님 말씀하신 것들이 잘 기억이 안나서 함부로 정하지 못할 것 같으니 의견 주셨으면 합니다.
feature_2dan처럼 그냥 2단 만들 브랜치 1회용으로 쓰고 마는건지 feature_dev 같이 크게크게 하는건지 정해야 한다고 생각합니다.**

**Comment by dozzzang** [comment]
수업 때 까지 잘 동작하지 않는다는 말씀은 곧 putty에서 잘 작동하지 않는다는 말씀일까요?
정리하면 branch 추가가 잘 안된다는 것 같은데 vscode로 하면 쉽게 할 수 있습니다.
https://hhhh88.tistory.com/43 vscode를 통한 깃 다루는 법 링크를 남기겠습니다.
feature을 통일 시켜야한다는 말씀이 'branch명을 정하는 규칙을 정하자'로 이해했는데 맞을까요?
feature_수행행위_수행대상 으로 하시는 건 어떨까요?
예를 들어 feature_create_webdesign feature_fix_web feature_implement_web 이렇게요.
그리고 커밋 단위에 대해서 고민해봤는데 공유하겠습니다.
https://jaeheon.kr/257
그리고 마지막 줄에 관해서는 예를 들어 웹 디자인 코드를 작성하는 경우 navbar,button등 기능이 많으므로
feature_create_web_design 브랜치를 우선 만든 후 이 브랜치 안에서 또 feature_navbar,feautre_button ... 을 만들어
feature_create_web_design 브랜치에 합친 후 rebase를 거치고 pull request 하는 것으로 알고 있습니다.
관련 링크는 https://velog.io/@jinuku/Git-%ED%98%91%EC%97%85-%EA%B0%80%EC%9D%B4%EB%93%9C#1-develop-%EB%B8%8C%EB%9E%9C%EC%B9%98%EC%97%90%EC%84%9C-feature-%EB%B8%8C%EB%9E%9C%EC%B9%98%EB%A5%BC-%EC%83%9D%EC%84%B1%ED%95%A9%EB%8B%88%EB%8B%A4 입니다.
저도 공부하는 단계이니 제가 이해한 게 맞는지, 다른 의견은 있는 지 피드백 주시면 감사하겠습니다.

**Comment by won-hj** [comment]
좋은 정보 감사합니다.

브랜치부분은 이해하신 것이 맞습니다.
부가설명을 하자면 저번주 수업 자료에서 깃플로우에 대해 언급을 한번 하셨습니다.
![image](https://user-images.githubusercontent.com/128560356/230779229-d5268324-d9f5-446a-9144-da0a41cdba0b.png)
이 사진처럼 feature_branch, develop, release_branch 이런 식으로 해야 할지 의견을 구하고 싶었습니다.
feature_create_webdesign feature_fix_web feature_implement_web 같이 하는 것도 좋은 방법 같습니다. 
최대한 이런 방식으로 커밋 단위를 잘 생각하겠습니다.

그리고 아직 혼동되는 부분이 있다면 putty를 거치지 않고 깃에 커밋해도 되는 것인지 입니다.
횡설수설하느라 제대로 전달될 수 없었던 것 같습니다.
어차피 깃으로 확인하는 것이니 로컬에서 연동만 한 후 putty를 사용하지 않아도 되는 것인지
아니면 그 안에 putty도 사용이 되는 것인지, 
또는 putty에서 전부 작업해야하는지에 대해 묻고싶었습니다.
혹시 수업때 교수님이 요구하시는 것이 무엇인지 기억하는게 있으시다면 의견 부탁드립니다....

그리고 전체적으로 공부해서 빠르게 적용시키겠습니다.
플라스크 설치 하는 브랜치로 일단 feature_installFlask 로 해보고 추후 실행하는 것과 묶어서 feature_flask로 통합하면 될 것 같습니다!

**Comment by dozzzang** [comment]
위에서 설명한 develop은 feature과 구분되는 개념이라고 이해하여 고려하지 않았습니다. 사용한다하면 사용할 수는 있으나 브랜치명에 Feature을 반드시 넣어야하는데 굳이라는 생각이 들어서요. ide를 뭐쓰세요? ide가 vscode라면 여기서  클론받고 애드하고 푸쉬할 수 있습니다. 주피터노트북도 마찬가지구요
