### ISSUE TITLE
오해했던점 + 추가 질문사항 

### ISSUE THREAD

**Issue by won-hj** [won-hj/mon2tor#52]
5월동안 아무것도 안하진 않았는데 알고보니 저번주랑 이번주 사이 도현씨 커밋한것이 너무너무 많았어서
날짜를 지난달로 착각했네요.......

혹시 커밋수 점이 하나 찍혀있으면 안에 파일 여러개여도 하나로 취급되는지 혹시 아시는 분 계시면 ...

**Comment by dozzzang** [comment]
네 커밋 점이 하나면 무조건 하나로 취급됩니다.
그래서 최대한 나눠서 올리는 게 좋아서 나눠 올리고 있습니다.

**Comment by KimEulJoong** [comment]
커밋 하나당 코드 3줄 이상 작성입니다. 알고 계시겠지만 참고바랍니다. 도현씨가 말씀하신것 처럼 최대한 세분화해서 커밋하시면 될것같습니다

**Comment by won-hj** [comment]
아하 ... 감사합니다... 3줄하고 커밋하겠습니다..
