### ISSUE TITLE
지금 문제점

### ISSUE THREAD

**Issue by won-hj** [won-hj/mon2tor#53]
커밋 좀 만지다가 뭔가 이상한 느낌이 들긴한데 
그래도 구조만 잘 만들어지면 금방 복구할 수 있을 것 같다는 생각은 듭니다

근데 지금 tool 있던 그거랑 config 바꾸는 그거랑 지금 문제가 좀 있습니다
뭐만하면 계속 merge 어쩌고 하면서 문제생겨서 
이걸 어떻게 하면 완전히 안뜨게 하는지도 문제고

아까는 문제좀 계속 있어서 나중에 처리한다 하고 풀리퀘스트부터 했는데(어차피 또 pr하면 되는거니까)
경로쪽 문제가 제가 말한대로 구분이 안됐더라구요 

2013~2022 랑 22273236이랑 구분하라고했었는데 전달이 잘 안됐나봐요
이부분 제가 env_set에서 수정 해놓고 메인에 pr할게요

-특수문자 제거
-파일 년도기준 구분 
이 될 것 같습니다

**Comment by dozzzang** [comment]
아직도 문제가 존재하나요?
feature_create_continuous_data와
feature_recreate_prediction_graph의 브랜치가 하나의 브랜치로 되면서 그런 것 같은데 아직 해결이 안됬다면
merge 어쩌고의 문제를 정확히 알 수 있을까요?

그리고 경로 수정은 알겠습니다.

**Comment by won-hj** [comment]
git pull feature_create_continuous_data 

From https://github.com/won-hj/mon2tor
 * branch            feature_create_continuous_data -> FETCH_HEAD
CONFLICT (file location): Data pipeline/2023-2027 csv 추출.py added in HEAD inside a directory that was renamed in 15b51e715bc7f7e454229de5135a762646312c0e, suggesting it should perhaps be moved to Data_pipeline/2023-2027 csv 추출.py.
Automatic merge failed; fix conflicts and then commit the result.

라고 뜹니다 
renamed라니까 뭔가 추측되는게 하나 있어서 이름을 다시 바꿔보니 해결됐습니다
tool을 config로 바꾸는 과정에서 pull하지 않고 바꿨더니 생긴 문제였네요
