### ISSUE TITLE
config(tool) 의 birthdeathdata와 worknonworkdata는 무슨 차이가 있나요?

### ISSUE THREAD

**Issue by won-hj** [won-hj/mon2tor#55]
각각 어떤 역할을 하고
어떻게 사용되는건지 알려주세요

**Comment by dozzzang** [comment]
birth death data는 사망자수와 출생아수 데이터이고
work nonwork data는 생산연령층 (15-64세) 고령인구(65세 이상) 데이터입니다.

**Comment by won-hj** [comment]
네 알겠습니다

**Comment by won-hj** [comment]
파일을 보면 13년도부터 22년도까지 따로 있고 
-2027이나 -2032같은 것들은 13년도부터의 내용이 있는데 이런 파일들은 어떻게 봐야하나요??
따로 있는 것들은 하나하나 그래프로 표현하고
합쳐져있는 것들은 그대로 모두 합쳐서 표현하는건가요?

또 work nonwork에서 -2022와 2013-2022의 차이는 뭔가요???

**Comment by dozzzang** [comment]
> 파일을 보면 13년도부터 22년도까지 따로 있고 -2027이나 -2032같은 것들은 13년도부터의 내용이 있는데 이런 파일들은 어떻게 봐야하나요?? 따로 있는 것들은 하나하나 그래프로 표현하고 합쳐져있는 것들은 그대로 모두 합쳐서 표현하는건가요?
### 따로 있다는 것이 출생아 수 사망자 수를 말씀하시는 거라면 년도마다 각각의 그래프를 보여주기 때문에 따로 있는 것이구요
### 13년도부터의 내용이 있는 이유는 예측할 때 13년도부터 데이터를 고려해야하기 때문에 13년도부터의 내용이 있는 것입니다.
### 하나의 csv당 하나의 그래프가 표현된다고 보면 됩니다.
> 또 work nonwork에서 -2022와 2013-2022의 차이는 뭔가요???
### 이름 수정을 한다는 것이 깜빡했네요 2013-2022는 과거-현재의 변화를 보여주는 추이 그래프용도이고 recreate_past_graph
### -2022와 같은 형식들은 prediction_graph용인데 인구만 고려했습니다.

**Comment by won-hj** [comment]
아하 알겠습니다 !
