### ISSUE TITLE
파일명이나 경로명 등에서 -랑 & 등 특수문자 되도록 쓰지 맙시다 !!! 

### ISSUE THREAD

**Issue by won-hj** [won-hj/mon2tor#56]
언더바가 아니더라도 더 사용가능한 문자들이 있겠지만
웬만하면 _만 사용하도록 하고
&라던지 -라던지 공백같은걸 보기 쉽다고 사용하는건 안좋은거같아요!!!!!

예를 들자면 -2022data.csv 같이 이름을 붙이셨는데
이거 리눅스같은데 명령어로 뭐 하려고 하면 대쉬때문에 무슨 이상한 옵션 어쩌고 하면서 안돼요!!!!

**$ mv -2022data.csv over2022/
mv: unknown option -- 2
Try 'mv --help' for more information.**

다음엔 조심합시다!!!!!

**Comment by dozzzang** [comment]
네
