### ISSUE TITLE
네이버 기사 크롤링

### ISSUE THREAD

**Issue by dozzzang** [won-hj/mon2tor#60]
네이버 기사 크롤링 시작하겠습니다.
나이를 입력했을 때 그에 대한 예측 그래프가 나올 것이고
아래에 저출산&고령화와 관련된 키워드를 설정하여 네이버 기사를 크롤링하여 정보를 제공할 예정입니다.
네이버 api를 이용할 예정입니다.

**Comment by dozzzang** [comment]
![image](https://github.com/won-hj/mon2tor/assets/74997120/7ce9ed06-da91-4166-adb7-0ebe416cc161)
Naver에서 자체 제공하는 공개 API를 등록하여 크롤링을 진행 했습니다.
201에러 : api 사용 목적을 명시하지 않음 (해결)

**Comment by dozzzang** [comment]
![image](https://github.com/won-hj/mon2tor/assets/74997120/9ac1896a-75a5-4c23-8058-8383cc445ed0)
test1 개선필요

**Comment by dozzzang** [comment]
![image](https://github.com/won-hj/mon2tor/assets/74997120/1269b87f-068e-411e-b8c8-a50062dde5c2)
test2 정제필요

**Comment by KimEulJoong** [comment]
해당 작업을 통해 예상되는 결과물의 형태는 어떠한 형태인가요? 나머지 웹 페이지 제작에 참고하고자 합니다.

**Comment by dozzzang** [comment]
![image](https://github.com/won-hj/mon2tor/assets/74997120/d2314f16-0d68-4b92-8b66-036caa2bd300)
위 사진과 같은 형식이 될 수 있습니다.
나이를 입력하면 나오는 창에서 footer(아래부분)에 넣고 싶습니다.

> 해당 작업을 통해 예상되는 결과물의 형태는 어떠한 형태인가요? 나머지 웹 페이지 제작에 참고하고자 합니다.

**Comment by dozzzang** [comment]
![image](https://github.com/won-hj/mon2tor/assets/74997120/1a2e16e5-3be8-46ea-a7dd-ecd7c8bf3aed)
test3 : 중복 제거 필요
동일한 날 제목의 순서가 바뀌어서 올라올 때가 있다. 따라서 전체 데이터를 고려하는 것이 아닌 연속된 데이터에서만 고려
전체 제목을 고려하는 것이 아닌 일정 글자수만 고려

**Comment by dozzzang** [comment]
test 4 : 제목 중복 제거 성공

**Comment by dozzzang** [comment]
test 5 : 텍스트와 숫자 이외 특수 문자 제거 성공

**Comment by dozzzang** [comment]
HTML 문서에 렌더링 하기 위하여 flask를 이용하여 코드를 구성 완료
HTML 완성될 시 TEST가능
키워드는 '저출산 산업'과 '고령화 산업' 두 가지로 크롤링을 수행하겠음

**Comment by dozzzang** [comment]
![image](https://github.com/won-hj/mon2tor/assets/74997120/08c1fb70-a54d-4fe5-ac1e-e3c1ab23ecd4)
입력한 나이에 따라 다른 크롤링 링크가 주어지도록 설정하였음
나이라는 var이 있어서 힘들었지만 POST -> GET으로 한꺼번에 구현하는데 성공함.
원래는 Description으로 링크화해서 보여주려고 하였으나, title로 보여주겠음. 다소 미완성된 느낌이 강하나 시간이 없으므로 패스

**Comment by dozzzang** [comment]
![image](https://github.com/won-hj/mon2tor/assets/74997120/dcffafaf-7e55-4afc-8bfd-90423aacafc0)
![image](https://github.com/won-hj/mon2tor/assets/74997120/fb8e23dd-6dcf-4d25-9246-a3c0c8169b3d)
이와 같이 title로 href화해서 보여주기 성공하였음.
제목이 정돈된 느낌은 아닌 것이 내가 정제없이 그냥 받아왔기 때문, 다만 시간이 없기에 되는 것만으로도 만족
그 아래에 그래프 + 설명 넣으면 될 듯
