### ISSUE TITLE
웹 페이지 구성 의견 요청

### ISSUE THREAD

**Issue by KimEulJoong** [won-hj/mon2tor#61]
![메인페이지1](https://github.com/won-hj/mon2tor/assets/127865678/eb99a6bb-2170-45de-af13-f84d1df37c5b)

메인페이지 현황입니다. 
나이를 입력하고 하단에 파란색 입력 버튼을 누르면 예측된 정보를 제공해 주는 페이지로 넘어가도록 설정하였습니다. 
그 아래의 인구 현황 그래프 예정 1과 그래프 예정2 에는 각각 -2022 graph와 work&nonwork 영역의 2023-2027_graph를 보여줄 예정입니다. 이 부분은 간편하게 이미지 파일로 첨부할까 생각중입니다. 
그래프 아래에는 연령계층별 추계인구 데이터를 30년부터 70년까지 10년단위로 나타낸 테이블 입니다.

왼쪽의 사이드바(메뉴바)는 사진과 같이 구성되어있고, 메인-장래인구추계는 메인페이지 / 메뉴-페이지는 인증과 예측 카테고리로 구성되어있으며 인증카테고리에서는 본인인증과 비밀번호 찾기 및 로그인 등의 기능이 있고, 예측 카테고리는 메인페이지에서 나이를 입력하면 넘어가게 되는 예측 정보 제공 페이지가 있을 예정입니다.  차트는 제작 과정에서 참고하기 위해 남겨두었으며 추 후 필요 없다면 제거할 예정입니다.

실제로 어떻게 나오는지 보시려면 bootstrap 브랜치 가셔서 index.html을 파일로 다운받아 실행하시면 편하게 웹 페이지를 확인할 수 있습니다. 
웹 페이지 구성에 추가적인 피드백 해주시면 오늘 안에 수정하도록 하겠습니다. 
웹을 완성하기 위해서 추가적으로 진행되어야 하는것들 
(1) 메인 페이지 그래프 이미지 추가
(2) 피드백 반영 후 수정
(3) 완성된 예측 그래프를 반영한 페이지 제작

편하게 의견 주시면 빠르게 반영해보도록 하겠습니다. 
포인트는 (3)번이고 웹 페이지 수정과 병행하여 진행될 예정입니다. (3)번에 대해서 완성한 python형식 그래프를 어떠한 방법으로 웹에 적용시킬것인지 생각하신 아이디어가 있으시다면 말씀해주세요. 아직 고민중이시라면 고민중이라고 말씀해주세요. 그럼 제가 일단 어떤 방법이든 이용해서 만들어볼께요.

**Comment by won-hj** [comment]
말씀하신것처럼 pyscript를 적용할 수 있으면 어느정도 하는 것도 좋은거같아요
대신 무언가 입력값에 대한 출력이 있어야하기 때문에 post나 get 방식 중 하나를 사용해야할거같습니다
변화가 수시로 있으면 pyscript로 하고 아니면 플라스크에서 왔다갔다 하는 것도 괜찮은 것 같습니다

그래프를 표현할 때 화면에 바로 띄우는게 아니라 url로 이미지를 가져와서 띄우는 방식입니다
따라서 html에 fetch 한줄만 추가해도 그래프를 보여줄 수는 있긴 합니다
그냥 보여주는 것은 이미지만 띄워주면 되는 문젠데
그 외로 더 추가적인 작업을 하거나 하면 html단에서 간단하게라도 바로바로 해주는 것이 낫지 않을까 생각합니다

그 외로는 도현씨 의견이 더 중요한거같고 
표현방법을 어떻게 할 것이냐가 제일 먼저 해결해야 할 문제라고 생각합니다.

**Comment by dozzzang** [comment]
![image](https://github.com/won-hj/mon2tor/assets/74997120/fa6e4b80-f793-4c33-be02-e040e6c51c53)
![image](https://github.com/won-hj/mon2tor/assets/74997120/a9fa9124-fe67-41ec-8e4e-8ad57e0f004b)
제가 을중씨씨의 부트스트랩을 보기 이전 구상도입니다.
table은 딱히 필요 ;없는 것 같습니다. 그래프로 대체하면 좋겠습니다. 하지만 테이블을 쓰고 싶다면 쓰셔도 됩니다.
웹을 구성하시는 분은 을중씨니까요.
우선은, 이용자의 관점에서 웹 페이지에 들어왔을 때 웹 페이지에 대한 설명&배경이 적혀 있어야한다고 생각했습니다.
그리고 과거 13년도부터 22년도까지의 출생아 수 사망자 수 그래프 '각각'을 html의 select box를 통해 골라서 볼 수 있게끔하는 공간을 마련했고
그 아래에는 생산인구&비생산인구의 추이 그래프 각각을 나타내는 공간을 마련하고
그 아래에 나이를 입력하는 box까지가
제가 구상한 main페이지입니다.
나이를 입력하고 페이지가 바뀌면 위 두 번째 사진과 같이 구상했습니다. 아래에는 크롤링한 기사 링크가 들어갈 것입니다.
텍스트 부분은 제가 다 채워넣을 수 있습니다. 을중씨가 원한다면 을중씨가 채워넣어도 좋습니다.
제 구상이 이렇다는 거지 을중씨가 더 가시적으로 표현할 방법이 계시다면 을중씨 소신껏 만들어도 좋습니다.
특히 로그인 ui부분과 커뮤니티 부분은 db를 구성하지 못하더라도 ui를 남기는 것만으로도 의의가 있을 것 같습니다.

**Comment by KimEulJoong** [comment]
확인하였습니다. 참고하여 수정하도록 하겠습니다. 모르는게 있으면 물어보겠습니다.
