### ISSUE TITLE
csv 경로명 및 작업 할 내용 확인 과 추가 변경사항 요청

### ISSUE THREAD

**Issue by won-hj** [won-hj/mon2tor#62]
이슈를 본 결과

- 셀렉트박스로부터의 입력값에 따라 13~22년도에 해당하는 출생아수/사망자수, 생산인구, 비생산인구로 각각 표현
- 텍스트 박스로부터 입력받은 값에 따라 22년도부터 예측하는 그래프 표현 

인 것으로 표현하면 완성인 것 같습니다

이것이 맞다면 두 번째에서 표현해주고 싶은 것이 무엇인지 제대로 나와있진 않은 것 같습니다.
파일을 확인한 결과 출/사와 생/비생도 예측할 데이터가 있습니다.
그렇다면 실질적으로 예측을 하는 화면은 어떻게 표현해낼 것인지 궁금합니다.
* 22년도까지의 내용과 같은 방법으로 한다면 단순히 각 그래프를 나열하는 방식만 생각하면 되는 문제일 것입니다
* 아니라면 어떻게 표현할 것인지 조금만 더 방향성을 잡아야 할 것 같습니다

또한 제가 했던 것은 13년도부터 22년도까지의 그래프를 각각 한꺼번에 나타내주었던 것입니다
근데 이렇게 한꺼번에 전부 띄워주는 것이 아니라 특정 기준에 따른 출력을 원하는 것이기 때문에 따로 출력하는 것으로 표현하면 될 것입니다.
여기서 제가 요구하고 싶은 것이 있는데 여러가지 파일들을 접근하는데 너무 따로따로 되어있는데다가 모듈로써 사용하기에 불편하기 때문에 구조를 조금 바꾸고 싶습니다.
클래스를 사용하여 13년도부터 22년도까지 한꺼번에 관리할 수 있는 객체를 만드는 식으로 바꾸고 싶습니다

경로명의 경우 birth_death와 work_nonwork로 나누고 데이터는 년도로만(2013, 2014 등) 사용하며, 
한번에 관리 할 모듈의 이름은 transition과 prediction으로 생각하고 있습니다

적절한지 의견 주세요!

**Comment by dozzzang** [comment]
셀렉트박스로 나타내는 것은 2013년부터 2022년까지의 출생아수/사망자수로 유일하고
생산인구/비생산인구는 년도를 따로 하지 않고 추이만을 나타냈기 때문에 셀렉트박스로 나타내는 것이 아니라 그냥 하나만 아래에 보여줄 생각입니다.

생산인구/비생산인구 예측 그래프는 그럼 어디다 쓰냐?했을 때 나이를 입력했을 때 보여줄 예정입니다.
근데 사실 웹에 삽입하는 것은 혁주씨이고 저도 이것을 구상해보았을 때 웹 사이트 공간을 html로 아무리 늘린다고 하여도 다 들어갈 수 없다고 생각하여 혁주님이 생각하신대로 한 것도 좋아보여요.

**Comment by won-hj** [comment]
아 어느정도 이해는 했습니다
해보고 중간중간 물어보겠습니다
