### ISSUE TITLE
로그인 기능 구현 : feature_flaskRouting 이용 방법 

### ISSUE THREAD

**Issue by dozzzang** [won-hj/mon2tor#64]
로그인 기능을 구현하고자 하는데 flask가 필요합니다.
기존에 만들어 놓으신 app.py에 수정하고자 하여 feature_flaskRouting을 pull받아 하고자 합니다.
따라서 app.py를 수정할 소요가 있으시다면 제 feature_login을 pull받아 작업하시면 나중에 merge할 때 conflict가 발생하지 않을 것 같습니다.

위 방법을 채택하려고 하였으나, local main이 feature_flaskRouting보다 훨씬 버전이 앞서 conflict가 발생하였습니다.
따라서 feature_flaskRouting의 branch를 생성해서 작업하도록 하겠습니다. 추후 작업할 때 이 사항 고려해주셨으면 합니다.

**Comment by dozzzang** [comment]
pull을 받아보니 자꾸 conflict가 나길래 무엇인가 했더니 제 local main이 혁주님의 branch보다 버전이 훨씬 앞이어서 conflict가 나는 것 같습니다. pr을 한 번 요청을 넣어주시면 제가 작업하기 편할 것 같습니다. 가능할까요?

**Comment by won-hj** [comment]
알겠습니다 !

점검좀 하고 문제 안생길 것만 커밋해서 pr 해두겠습니다

**Comment by dozzzang** [comment]
> 알겠습니다 !
> 
> 점검좀 하고 문제 안생길 것만 커밋해서 pr 해두겠습니다

아닙니다! 원하실 때 pr하셔도 됩니다. 다만, 제가 브랜치를 생성해서 마지막에 주석처리가 덜 된 부분을 수정하는 것이 그냥 혁주님의 branch에서 해버렸네요. 
그 이후로는 따로 branch따서 작업하겠습니다.

**Comment by won-hj** [comment]
주석은 괜찮습니다!!!!!
왠지 pull하라고 계속 뭔가 생기던데 그것 때문이었나보네요
다행입니다
덕분에 좋죠~
