### ISSUE TITLE
pr 확인해주세요!

### ISSUE THREAD

**Issue by won-hj** [won-hj/mon2tor#65]
잘 된건지 모르겠긴한데 문제 없으면 저 정도로 일단 해도 괜찮을 것 같습니다!

지금 할 것은 figure 활용에 쉽게 만들고,
잘 작동하는지가 첫번째 같습니다 !

- 2013~2022 각 그래프 각각 출력
- 2013-2022 그래프 출력
- 2022년 이후 그래프들 각각 출력
을 기본으로 구조를 좀 보기 쉽고 쓰기 쉽게 만드는 것이 될 것 같습니다.

**Comment by dozzzang** [comment]
![image](https://github.com/won-hj/mon2tor/assets/74997120/aa5eff8d-4572-40a6-908c-d224b83ceac3)
음 return json 형식이라 json으로만 나오는 것 같은데 혹시 그래프로 나오셨을 때 코드가 이와 동일했었나요?
return render_template형태가 되어야 하지 않나요? 우선 저도 수정해보겠습니다.

**Comment by won-hj** [comment]
저건 저렇게 나오는게 맞아요
화면상에는 json으로 데이터만 보내버리는거고 (json.dump)
실질적으로 화면에 올리는건 html상에서 fetch(dump)하면서 href에 추가해둔 보케나 이런 라이브러리들로 그래프 표현을 해주는거에요

함수가 두 개 있는건데
하나는 저렇게 표시해줄 데이터만 따로 덤프하는거고
다른 하나는 render해주는 함수에요

**Comment by dozzzang** [comment]
> 저건 저렇게 나오는게 맞아요 화면상에는 json으로 데이터만 보내버리는거고 (json.dump) 실질적으로 화면에 올리는건 html상에서 fetch(dump)하면서 href에 추가해둔 보케나 이런 라이브러리들로 그래프 표현을 해주는거에요
> 
> 함수가 두 개 있는건데 하나는 저렇게 표시해줄 데이터만 따로 덤프하는거고 다른 하나는 render해주는 함수에요

아아 print_graph 파일들이 있었군요 src에 있었군요 꼼꼼하지 못했네요 죄송합니다

**Comment by won-hj** [comment]
죄송할건 없습니다 !!!
근데 지금 print_graph랑 그림을 그려주는 파일들 전체적으로 구조를 조금 바꾸려고 해서
그냥 표현이 된다는 것만 보면 좋을 것 같습니다

**Comment by dozzzang** [comment]
근데 어떻게 표현이 되는 것인가요?
우선 경로가 Print_graph에서 birth'\'&death_data에서 \을 빼었고 print_graph는 경로를 살짝 추가해주었습니다. 경로 에러가 나서
![image](https://github.com/won-hj/mon2tor/assets/74997120/bfbe2382-224e-472c-aa75-babced554d92)
저는 이렇게 나오는데, 사실 저는 바로 그냥 flask있는 곳에 렌더링한 것을 return하고 html을 수정하는 방식으로만 해왔어서 혁주님의 방식은 처음이여서 어떻게 하면 볼 수 있을 지 잘 모르겠습니다.
알려주시면 감사하겠습니다.

**Comment by won-hj** [comment]
위의 에러는 해결되었고 아래에서 보는게 맞죠?? 

간단하게 함수 아무거나 만들어보자면
@app.route('/render')
def render():
    return render.template("render.html")
같이 원초적으로 렌더 함수를 만들 수 있겠고

(dump하는건 url없어도 되는거같긴한데 갑자기 헷갈리네요 url을 따오는 방식이라 있어야하는거같디고하고... 감안해주세용..)
@app.route('/dump')
def dump():
    #내용
    return json.dump(json.item(plot([figures]), 'div_id')
덤프하는 함수 이런 식으로 만든다고 하면

html에서는
<body>
<div id = 'div_id'> </div>
<Script> fetch(/dump).then(function(responce){ return response.json();})
                                     .then(function(item) { return  Bokeh.embed.embed_item(item);}) </Script>
</body>

같은 식으로 div만들어서 id는 지정해줄 수 있는게 있으면 없어도 되긴하고 fetch로 url 가져와서 함수로 어떻게 어떻게 한다 라는게 기본 개념이에요

근데 저기선 거의 기본적인거라 바뀌는게 엄청 크진 않을거고

html 하면서 {{ 변수명(이거 자세히 기억이 안나네요 죄송..) }} 이렇게 하고
flask 상에서 아얘 구성해서 넘겨주는 방식도 있습니다

**Comment by dozzzang** [comment]
아직 웹으로 보여지게끔 구성은 안하고 넘겨주는 방식에 대한 메소드만 구현한 것이 맞죠?

**Comment by won-hj** [comment]
네 아직은 넘겨주는 것만 했었습니다.

제가 생각하던건 어떤 하나의 파일에서 다른 그래프들을 관리하게끔 하려했는데
어제 했던 것도 생각대로도 안됐지만 이상하게 하고 있었는데다
도현님 속도 생각하면 너무 느린거같아서
일단 주먹구구같아도 기능구현을 우선으로 해야할거같아요
리팩토링도 마지막에 해야하는건데 너무 먼저 생각한거같고
어차피 웹 상에서는 플롯 하나로만 구성해 넘겨줄 것이니 각 입력값에 맞는 그래프 출력을 우선으로 하겠습니다
만들어주셨던 print_graph 안의 show()해주는 파일들을 다 써보려했는데
잘 안되네요
그냥 새로 만들어서라도 해야할 것 같습니다

**Comment by dozzzang** [comment]
그렇군요
저도 빠르게 로그인/로그아웃/회원가입 기능 추가하고 돕겠습니다. 사실 가장 급한 건 그 부분이네요.

**Comment by won-hj** [comment]
음 printgraph 쪽 지금 확인해보는데 갑자기 출력이 안되네요.....
경로문제있다고하는데 제가 전에 했던거랑 다르게 했었거나 그런 문제가 있는 것 같아요
최대한 빨리 해결하는게 우선같습니다

**Comment by won-hj** [comment]
전에 커밋하면서 문제 있었던 이후로 os.path.join()을 안쓰고 문자열로만 했던거랑 경로 합친걸 보고 뭐가 문젠지 몰랐는데
printgraph는 고쳤습니다

**Comment by dozzzang** [comment]
네 일단 알겠습니다. 전 리눅스 OS에서 작업하셔서 다른건가? 했었습니다.
고쳐서 다행이군요.
