### ISSUE TITLE
login.html,register.html 변경

### ISSUE THREAD

**Issue by dozzzang** [won-hj/mon2tor#66]
index.html은 일단 냅두고
login.html과 register.html 을중 씨 브랜치에서 수정하겠습니다.
기능 구현을 위해 쓸 데 없는 것이 많아서 그냥 새로 부트스트랩을 이용하여 엎어보려고합니다.
추가로 web은 templates 폴더로 이름 변경하는 것이 좋을 것 같아 변경하겠습니다.

**Comment by dozzzang** [comment]
이와 관련해서 한 번 PR 요청 해주시면 좋을 것 같습니다.

**Comment by KimEulJoong** [comment]
pr 하였습니다
