### ISSUE TITLE
예측 데이터 중에서 2036년도를 37로 바꿀 수 있을까요?

### ISSUE THREAD

**Issue by won-hj** [won-hj/mon2tor#67]
다른 파일들은 5년단위로 되어있는데 36년도만 4년단위네요 계속 불러오지 못해서 보니 이것만 4년이었습니다....
내용도 36년까지로만 되어있는데 어떻게 바꾸면 좋을까요??

그리고 지금 printgraph를 생산/고령인구로 바꾸고 있습니다.

현재 주먹구구같아도 특정년도 입력값을 줬을 때 출/사 생/고 그래프 두개를 출력할 수 있습니다.

**Comment by dozzzang** [comment]
36년도부터 음수 값이 도출되어 36년까지만 하였었습니다.
만약에 37년까지 보고 싶다면 예측 코드를 수정하면 되긴 합니다. 메소드가 5년 단위로 불러오시는 것이라면 수정할까요?
진행상황 확인했습니다.

**Comment by won-hj** [comment]
미래 예측 데이터는 22 27 32 로 5년단위인데 비해 마지막 파일만 36년도로 4년차이여서 입니다!!
아니면 앞에만 5ㅈ년씩하고 마지막만 따로 불러온다던지 해도 되긴한데 ..... 
수정해주시면 좀 더 깔끔해보일 수 있는 여지가 생기긴 합니다......

**Comment by dozzzang** [comment]
> 미래 예측 데이터는 22 27 32 로 5년단위인데 비해 마지막 파일만 36년도로 4년차이여서 입니다!! 아니면 앞에만 5ㅈ년씩하고 마지막만 따로 불러온다던지 해도 되긴한데 ..... 수정해주시면 좀 더 깔끔해보일 수 있는 여지가 생기긴 합니다......

수정하고 Pull Request 올렸습니다. merge 바랍니다.

**Comment by won-hj** [comment]
제가 착각한게 있는것같습니다
pipeline과 tool 모두 사용하는건가요??
tool같은 경우는 config로 바꿔서 사용하는게 아닌가 싶은데 어떻게 되는건지 잘 모르겠습니다

또 예측 그래프의 경우 그냥 22년도부터 4개 파일을 이용해 다른 통계 그래프랑 같은 방식으로 표현하는게 아닌가보네요???

**Comment by won-hj** [comment]
정리하자면 
과거 통계 그래프는 특정 입력값에 맞춰 출생아/사망자 수로 각각 하나씩 출력하고
생산가능/고령인구 수 는 통합된 하나의 그래프만 출력하는데 
여기에 사용하는게 bokeh를 이용한 것이고

예측 그래프는 prophet을 이용해 show() 들어가거니 비슷한 것들을 이용해서
생산고령 그래프만 딱딱 출력하면 되는게 맞나요???

그리고 pr 내용 보면 continuous와 prediction 브랜치의 데이터 업데이트 둘 다 내용이 같은데
무슨 차이가 있나요?
두 브랜치 모두 pr을 해야하나요??

**Comment by won-hj** [comment]
생산/고령자수 2013-2022 파일에서 
Year,work_percent,nonwork_percent,work_demo,nonwork_demo
2013,73.4,11.9,3701,602
2014,73.4,12.4,3725,627
2015,73.4,12.8,3744,654
2016,73.4,13.2,3759,675
2017,73.2,13.8,3757,706
2018,72.9,14.3,3762,736
2019,72.7,14.9,3762,768
2020,72.1,15.7,3737,815
2021,71.6,16.6,3702,857
2022,71,17.5,3667,901
로 되어있는 것을 
for iteration,99999
출생아수,272337
사망자수,305086
생산가능인구(15-64),373790
고령인구(65-),81520
같은 식으로 바꿔도 될까요? 

아니면 방향만 바꿔서 
year ~~
workpercent ~~
nonworkpercent ~~~ 
같은 식으로 바꿔도 될까요?

**Comment by dozzzang** [comment]
> 제가 착각한게 있는것같습니다 pipeline과 tool 모두 사용하는건가요?? tool같은 경우는 config로 바꿔서 사용하는게 아닌가 싶은데 어떻게 되는건지 잘 모르겠습니다
> 
> 또 예측 그래프의 경우 그냥 22년도부터 4개 파일을 이용해 다른 통계 그래프랑 같은 방식으로 표현하는게 아닌가보네요???

두 개 합쳐서 config로 둬도 무방할 것 같습니다.
두 번째 말씀은 무슨 말인지 이해가 안갑니다. 다른 통계 그래프라함은 무슨 그래프를 의미하는 것이지요?

**Comment by dozzzang** [comment]
> 정리하자면 과거 통계 그래프는 특정 입력값에 맞춰 출생아/사망자 수로 각각 하나씩 출력하고 생산가능/고령인구 수 는 통합된 하나의 그래프만 출력하는데 여기에 사용하는게 bokeh를 이용한 것이고
> 
> 예측 그래프는 prophet을 이용해 show() 들어가거니 비슷한 것들을 이용해서 생산고령 그래프만 딱딱 출력하면 되는게 맞나요???
> 
> 그리고 pr 내용 보면 continuous와 prediction 브랜치의 데이터 업데이트 둘 다 내용이 같은데 무슨 차이가 있나요? 두 브랜치 모두 pr을 해야하나요??


첫번째 문장 두 번째 문장 모두 맞습니다.
생산가능/고령인구 수 과거는 추이만 보여줬습니다. 통합으로 
네 두 브랜치 모두 pr해야합니다. 두 브랜치를 하나의 브랜치에서 작업해서 업데이트가 같다고 나오는 것 같습니다.
혁주님이 요구한대로 work&nonwork와 birth&death 모두 2036년까지 예측하는 것에서 2037년까지 예측하는 것으로 수정하였고
그에 따라 데이터도 업데이트한 것입니다.

**Comment by dozzzang** [comment]
> 아니면 방향만 바꿔서
year ~~
workpercent ~~
nonworkpercent ~~~
같은 식으로 바꿔도 될까요?

아니요. 권장하지 않습니다. 통일 시켜주지 못한 점은 죄송합니다. 고려를 못했었네요.
원래는 위 처럼 Year, .... , .... , ... 형식이 맞는데 제가 보기 편하게 한다고 그렇게 되었었네요.
문제가 있나요?
만약 저렇게 바꿔야한다면 코드를 다 고쳐야합니다.

**Comment by won-hj** [comment]
1. 다른 통계 그래프는 bokeh사용 통계 그래프(2013~2022)를 말하는 것입니다.
2. 그렇다면 pr 하겠습니다
3. 그런 문제가 있다면 제가 다른 방법을 찾아보는게 좋을 것 같습니다. 그런데 그렇다면 2013~2022년도까지의 생산자/고령자 수 그래프를 bokeh로 나타내주는것이 맞나요?? 
4. 마지막으로 prophet 은 pip로 설치해야하나요? 초반엔 자동으로 색칠되어있었던것으로기억하는데 어느순간 흰색으로 표시되네요 해야한다면 버전은 몇으로 해야하나요?

**Comment by won-hj** [comment]
생산/고령자수 2013-2022년도 그래프 표현은 어떻게 될까요?
각 년도 당 평균을 보여주는건지
따로 보여줘야하는건지 궁금합니다!!

같은 gridplot으로 보여준다면 따로는 표현하지 못할 것 같은데 
그렇다면 평균이 맞는거겠죠?

**Comment by dozzzang** [comment]
아 봤었는데 이제 다시 답해주네요.
prophet 버전은 1.1.2입니다. fbprophet이 아닌 prophet만 설치하셔야합니다.
생산/고령자 수 저번부터 무슨 말인가 싶었는데 제가 과거 그래프를 생산하며 이미 생산/고령자 수 그래프를 gridplot으로 제공했었군요.. 2달 전에 한 일이라 제공 안한 줄 알고 추이를 제공하는 그래프를 따로 만들었던 건데 이와 관련해선 제가 메인웹페이지를 공유해드리겠습니다.

**Comment by won-hj** [comment]
넵 설치 했습니다
