### ISSUE TITLE
readme.md 수정했습니다

### ISSUE THREAD

**Issue by dozzzang** [won-hj/mon2tor#68]
Contributor 부분에 각자 개인정보 기입해주시길 바랍니다.
추가로 자기가 넣고 싶은 것이 있으면 자유롭게 넣어 주시길 바랍니다.
readme는 여유롭게 하루 전에 완성하고 싶습니다. 따라서 프로젝트가 하루 전에 마무리 되었으면 합니다.

**Comment by won-hj** [comment]
알겠습니다 빨리 해보겠습니다 !!!!

**Comment by KimEulJoong** [comment]
넵

**Comment by dozzzang** [comment]
리드미랑 requirements 재수정했습니다. pr 받아주시면 감사하겠습니다.
