### ISSUE TITLE
index.html 수정해도 되나요?

### ISSUE THREAD

**Issue by dozzzang** [won-hj/mon2tor#73]
과거 그래프 1. 출생아 / 사망자 2. 생산가능 / 고령을 다른 페이지에 보여주게 하는 것이 낫지 않을까요?
flask로 route지정하기도 쉬우니까요 삽입하시는 코드만 성공하시면 제가 html에 넣겠습니다.

**Comment by KimEulJoong** [comment]
index 파일 수정을 하시겠다는 말씀이시죠? 첫번째 페이지에 들어갈 예정이었던 과거 그래프를 다른 페이지로 옮기겠다는 말씀이신가요? 알겠습니다. 
그리고 혹시 flask로 route지정하여 html문서에서 그래프 정상적으로 불러와 지는지 확인하신 분 계신가요? jupyter notebook과 vsc의 호환성 문제로 인하여 에러가 떠서 실패하였습니다. 제가 알아본 바로는 해결하기 위한 다양한 방법에 모두 기존 python 그래프 파일 코드를 수정할 필요가 있어 보여서 잠시 다른 방법을 찾아보고 있습니다.

**Comment by won-hj** [comment]
출생아사망자수 그래프의 경우 년도를 어떻게 입력을 html에서 받아와 넘길 것인지 같은 방법을 생각하면 되고
나머지 다른 구조의 경우 지금 csv 파일을 읽어오는 과정을 지금 생각하고 있습니다
어제 자기 전까지는 각 행단위로 리스트로 만드는 것 까지는 해놨는데 
이걸 다른 함수로 따로 빼는게 나을거같아서 그걸 구상중이고
그래프 출력보다는 html단에서 flask로 어떻게 입력을 줘서(get post 등) 어떻게 분류를 하냐 가 문제인 것 같은데 
이건 좀 시도좀 해봐야할 것 같습니다
