### ISSUE TITLE
main page 수정완료했습니다. 이에 따라 그래프 표현을 쉽게 하는 방법 생각 공유

### ISSUE THREAD

**Issue by dozzzang** [won-hj/mon2tor#76]
![image](https://github.com/won-hj/mon2tor/assets/74997120/ca979d49-7987-471d-b44e-2075a409a13b)
![image](https://github.com/won-hj/mon2tor/assets/74997120/fbd9347d-51c6-448f-93df-fc08e245dcb6)

사실 별로 폼이 안나긴합니다. 오랜만에 해서 잘 안되네요..

나이 입력 후 엔터 누를 시 --> 그래프 그냥 일단 다 넣고 그에 따른 설명 쭉 적어놓고 밑에 크롤링 data 제거 이 때 나이는 15-60?까지만 입력받을 수 있도록 설정하고 3살 단위에 따라 다른 크롤링 데이터 제공

왼쪽 그림 클릭 시 --> 그래프를 보는 설명 텍스트 기입 + past graph 쭉 제공
오른쪽 그림 클릭시 -> 추이 past graph만 제공 (설명 안에 기재되어 있음)

이 3개의 웹페이지만 구현하면 끝입니다.

**Comment by won-hj** [comment]
- 오른쪽 그림 클릭시 -> 추이 past graph만 제공 (설명 안에 기재되어 있음)
에서 추이 past graph만 제공이라는 말씀은
![image](https://github.com/won-hj/mon2tor/assets/128560356/dfd975ff-967e-4447-aa1f-383bbbf267f4)
이 6개만 출력하는게 맞나요?

**Comment by KimEulJoong** [comment]
작업 브랜치가 어디인가요? 그래프는 어떠한 방식으로 적용하셨나요?

**Comment by dozzzang** [comment]
> 작업 브랜치가 어디인가요? 그래프는 어떠한 방식으로 적용하셨나요?

fixweb, 저기 나오는 그래프는 href용 image입니다.

**Comment by dozzzang** [comment]
> * 오른쪽 그림 클릭시 -> 추이 past graph만 제공 (설명 안에 기재되어 있음)
>   에서 추이 past graph만 제공이라는 말씀은
>   ![image](https://user-images.githubusercontent.com/128560356/243428641-dfd975ff-967e-4447-aa1f-383bbbf267f4.png)
>   이 6개만 출력하는게 맞나요?

예측 그래프는 나이 입력 했을 때만 나오게 하고, 추이 그래프는 past_graph중에 work&nonwork 모든 년도 출력한 파일 하나만 출력하려고 합니다.
