### ISSUE TITLE
Pull Request 확인 바랍니다.

### ISSUE THREAD

**Issue by dozzzang** [won-hj/mon2tor#81]
아마 main에 merge하고 pull 받으시면 conflict날 겁니다. 
이전 파일과 이후 파일을 분할 창으로 보여주는 것이 있을텐데 그 곳에서 왼쪽에서 점 3개있는 것을 클릭하여 left를 반영한다하면
app.py는 제꺼로 받고 혁주님이 작성한 코드를 어디에 백업해둬서 수정하는 것을 추천드립니다.
파일 정리는 마지막에 합시다.
우선은 과거 그래프삽입과 미래 그래프 삽입만 되면 끝입니다.
오늘 내로 가능할까요?

**Comment by won-hj** [comment]
pr은 했습니다
app 내용 싹 다른데 옮겨놓고 머지 받으면서 조절하겠습니다

그래프가 문제되는 worknonwork 추이 빼고는 값만 잘 주면 잘 나오기 때문에 다른 문제만 생기지 않는다면 오래 걸리진 않을 것 같아요!
대신 나이를 입력받는 부분에서 어떤 그래프를 어떻게 처리하냐, (이름생각 안남) 하단 두 파트에서 어떤 그래프를 어떻게 보여줄 것이냐 가 고민해볼 문제인데
이건 정리해서 올릴게요
그리고 
이제봤는데  db쪽에서 db라길래 그냥 db만 적용하셨겠거니 했는데 .ignore 적용 전 내용이 들어가있네요...
homekey.pub 은 괜찮은데 비밀키도 들어가 있었습니다....... 
머지해버린걸 되돌리고 다시 해야할 것 같은데 어떻게 생각하시나요?... 
확인했어야 했는데 죄송합니다 ..

**Comment by dozzzang** [comment]
> pr은 했습니다 app 내용 싹 다른데 옮겨놓고 머지 받으면서 조절하겠습니다
> 
> 그래프가 문제되는 worknonwork 추이 빼고는 값만 잘 주면 잘 나오기 때문에 다른 문제만 생기지 않는다면 오래 걸리진 않을 것 같아요! 대신 나이를 입력받는 부분에서 어떤 그래프를 어떻게 처리하냐, (이름생각 안남) 하단 두 파트에서 어떤 그래프를 어떻게 보여줄 것이냐 가 고민해볼 문제인데 이건 정리해서 올릴게요 그리고 이제봤는데 db쪽에서 db라길래 그냥 db만 적용하셨겠거니 했는데 .ignore 적용 전 내용이 들어가있네요... homekey.pub 은 괜찮은데 비밀키도 들어가 있었습니다....... 머지해버린걸 되돌리고 다시 해야할 것 같은데 어떻게 생각하시나요?... 확인했어야 했는데 죄송합니다 ..

1. 그냥 일단 페이지에 삽입만 다 성공한다면 제가 html을 이용해서 구성은 고치겠습니다.
2. 네 revert할 수 있습니다. 둘 다 revert해야하나요? .gitignore은 혁주님의 branch에 있는건가요? 그렇다면 혁주님의 branch가 먼저 merge되고 제가 또 pull받아서 conflict해결하고 다시 pr하나요?

**Comment by won-hj** [comment]
커밋내역 보니 revert는 db만 하면 될거같아요
.gitinore 만 app있는 곳에 하나 만들어두고 안에 원하는 몇줄 추가하는게 끝이니 .homekey 랑 __pycache__ 만 한 줄에 하나씩 넣기만해도 되는 문제라 브랜치 브랜치까지 어떻게 안해도 되지 않을까 싶어요 괜히 충돌날거같은 느낌이 드네용........

############
일단 쓸데없는짓 안하려면 확인할게 있습니다

어제 본 app의 5가지 함수 index login past1 past2 prediction 기준으로 머지한 두가지 브랜치로부터 업데이트(past2, prediction, login logout register, index )가 되는게 맞나요??
past1을 찾을 수 없는데 어떻게 되는 건가요??
+
각 기능마다 무엇을 클릭하면 어떤 함수로 연결되는지 정확히 알아야할것같아요
어제 본 화면 기준으로 쓰겠습니다(머지문제로 아직 업데이트 안했으니까요)

나이입력 -> 입력받은 나이를 어떻게 표현해야 좋을까요? 데이터들은 13~22까지 과거거나 미래는 22 27 32 37로 5년단위 구분인데 이부분을 자세히 하고싶습니다
왼쪽하단 -> 과거와 현재의 실제수치라는 의미가 정확히 어떻게 되나요? past 1인지 2인지와 동작은 어떻게 하나요(전체 출력?)??? 
오른쪽하단 -> 과거와 현재의 추이라는 의미와 추이같은 경우는 문제가 있던 부분인데 어떻게 해결 할 아이디어나 따로 해결책이 있으신가요?
크롤링 결과는 어떤 부분에서 동작하고 결과는 어디서 확인하나요?

**Comment by dozzzang** [comment]
> 커밋내역 보니 revert는 db만 하면 될거같아요 .gitinore 만 app있는 곳에 하나 만들어두고 안에 원하는 몇줄 추가하는게 끝이니 .homekey 랑 **pycache** 만 한 줄에 하나씩 넣기만해도 되는 문제라 브랜치 브랜치까지 어떻게 안해도 되지 않을까 싶어요 괜히 충돌날거같은 느낌이 드네용........
> 
> ############ 일단 쓸데없는짓 안하려면 확인할게 있습니다
> 
> 어제 본 app의 5가지 함수 index login past1 past2 prediction 기준으로 머지한 두가지 브랜치로부터 업데이트(past2, prediction, login logout register, index )가 되는게 맞나요?? past1을 찾을 수 없는데 어떻게 되는 건가요?? + 각 기능마다 무엇을 클릭하면 어떤 함수로 연결되는지 정확히 알아야할것같아요 어제 본 화면 기준으로 쓰겠습니다(머지문제로 아직 업데이트 안했으니까요)
> 
> 나이입력 -> 입력받은 나이를 어떻게 표현해야 좋을까요? 데이터들은 13~22까지 과거거나 미래는 22 27 32 37로 5년단위 구분인데 이부분을 자세히 하고싶습니다 왼쪽하단 -> 과거와 현재의 실제수치라는 의미가 정확히 어떻게 되나요? past 1인지 2인지와 동작은 어떻게 하나요(전체 출력?)??? 오른쪽하단 -> 과거와 현재의 추이라는 의미와 추이같은 경우는 문제가 있던 부분인데 어떻게 해결 할 아이디어나 따로 해결책이 있으신가요? 크롤링 결과는 어떤 부분에서 동작하고 결과는 어디서 확인하나요?

past1을 어디서 찾을 수 없다는 것인지 모르겠네요 app.py인지 past1.html인지
index는 메인화면이고 login은 로그인이고 past1은 왼쪽 그림 클릭이고 past2는 오른쪽 그림 클릭이고 prediction은 나이 입력하고 엔터치시면 돼요
나이입력하면 그냥 prediction_graph에 있는 거 쭉 다 넣어주시기 바랍니다. 배치는 제가 하겠습니다.
실제수치는 그냥 past_graph에 2013~2022까지 있는 거 다 넣으면 되고요 추이는 past_work_nonwork만 넣으면 됩니다.
보시면 실제수치는 인구수가 나오고 추이는 %로 나와요
문제가 있다는 게 저는 잘 나와서 안되시면 제가 할게요

크롤링 결과는 크롤링 브랜치에 업데이트해놨습니다. 닫아놨는데 읽어보시면 될 듯해요. 코드도 있고요. 한 번 app.py로 이것저것 해보시길 추천드립니다.

**Comment by dozzzang** [comment]
past1에 past_graph들 2013부터 2022까지 렌더링 past2에 past_work_nonwork 렌더링 prediction에 5년 단위로 나오는 prediction graph 모조리 렌더링 해주시면 구조 수정은 제가 해보겠습니다.

**Comment by won-hj** [comment]
넵 알겠습니다 !
