### ISSUE TITLE
past graph2 페이지에 그래프 출력 안되는데 저만 그런건가요?

### ISSUE THREAD

**Issue by KimEulJoong** [won-hj/mon2tor#87]
코드 보니까 출력을 의도한것이 맞는데 출력이 안되는것같습니다. 제 환경에서만 그런건지 확인부탁드립니다.

**Comment by KimEulJoong** [comment]
해당 코드를 우선 문제라고 인식하고 수정해놨습니다. 다른 분들이 정상 작동된다면 문제없지만 출력이 마찬가지로 안된다면 제가 수정한 파일을 pr하겠습니다

**Comment by dozzzang** [comment]
네 안 되는 것으로 하기로 했습니다. 수정했다는 것은 된단 말인가요?
